window.KnowledgeTree = window.KnowledgeTree || {};
Object.assign(window.KnowledgeTree, {
  "Matematyka": [
    "Liczby naturalne i całkowite", "Ułamki i liczby wymierne", "Liczby niewymierne i rzeczywiste", "Prawa działań arytmetycznych", "Potęgowanie i pierwiastkowanie",
    "Logarytmy i ich własności", "Wyrażenia algebraiczne", "Wzory skróconego mnożenia", "Równania liniowe", "Nierówności liniowe",
    "Układy równań liniowych", "Pojęcie funkcji i jej dziedziny", "Zbiór wartości funkcji", "Funkcja liniowa", "Funkcja kwadratowa",
    "Postać kanoniczna i iloczynowa", "Wielomiany", "Dzielenie wielomianów", "Twierdzenie Bézouta", "Funkcje wymierne",
    "Asymptoty funkcji", "Funkcja wykładnicza", "Funkcja logarytmiczna", "Miara łukowa kąta (radiany)", "Funkcje trygonometryczne (sinus, cosinus, tangens)",
    "Wzory redukcyjne", "Równania trygonometryczne", "Ciągi liczbowe", "Ciąg arytmetyczny", "Ciąg geometryczny",
    "Granica ciągu", "Liczba e (podstawa logarytmu naturalnego)", "Szeregi liczbowe", "Szereg geometryczny i jego suma", "Granica funkcji w punkcie",
    "Granice jednostronne", "Ciągłość funkcji", "Pochodna funkcji w punkcie", "Interpretacja geometryczna pochodnej", "Wzory na pochodne funkcji elementarnych",
    "Pochodna sumy, iloczynu i ilorazu", "Pochodna funkcji złożonej", "Monotoniczność a znak pochodnej", "Ekstrema lokalne funkcji", "Druga pochodna",
    "Wypukłość, wklęsłość i punkty przegięcia", "Reguła de L'Hospitala", "Badanie przebiegu zmienności funkcji", "Zadania optymalizacyjne", "Wzór Taylora i Maclaurina",
    "Różniczka funkcji", "Całka nieoznaczona", "Podstawowe wzory całkowe", "Całkowanie przez podstawienie", "Całkowanie przez części",
    "Całkowanie funkcji wymiernych", "Całkowanie funkcji trygonometrycznych", "Całka oznaczona (wzór Newtona-Leibniza)", "Pole obszaru płaskiego", "Całka niewłaściwa",
    "Długość łuku krzywej", "Objętość bryły obrotowej", "Pole powierzchni bryły obrotowej", "Funkcje dwóch i wielu zmiennych", "Dziedzina funkcji wielu zmiennych",
    "Granica i ciągłość funkcji wielu zmiennych", "Pochodne cząstkowe pierwszego rzędu", "Pochodne cząstkowe wyższych rzędów", "Gradient funkcji", "Pochodna kierunkowa",
    "Płaszczyzna styczna i wektor normalny", "Ekstrema lokalne funkcji wielu zmiennych", "Hesjan (macierz drugich pochodnych)", "Ekstrema warunkowe", "Metoda mnożników Lagrange'a",
    "Metoda najmniejszych kwadratów (ujęcie analityczne)", "Całka podwójna", "Całka iterowana", "Zamiana zmiennych w całce podwójnej (współrzędne biegunowe)", "Zastosowania całek podwójnych",
    "Całka potrójna", "Współrzędne walcowe", "Współrzędne sferyczne", "Zastosowania fizyczne całek wielokrotnych", "Krzywe parametryczne",
    "Całka krzywoliniowa nieskierowana", "Całka krzywoliniowa skierowana", "Twierdzenie Greena", "Potencjał pola wektorowego", "Całka powierzchniowa",
    "Twierdzenie Gaussa-Ostrogradskiego", "Twierdzenie Stokesa", "Równania różniczkowe zwyczajne pierwszego rzędu", "Równania o zmiennych rozdzielonych", "Równania różniczkowe liniowe pierwszego rzędu",
    "Zagadnienie początkowe Cauchy'ego", "Równania różniczkowe zupełne", "Równania różniczkowe wyższych rzędów", "Równania liniowe o stałych współczynnikach", "Metoda przewidywań",
    "Metoda uzmienniania stałych", "Układy równań różniczkowych", "Transformata Laplace'a", "Równania różniczkowe cząstkowe (równanie ciepła, falowe)", "Metody numeryczne rozwiązywania równań (np. metoda Eulera, Rungego-Kutty)"
  ],
  "Algebra liniowa": [
    "Pojęcie skalara i wektora", "Wektory w R^2 i R^3", "Dodawanie wektorów i mnożenie przez skalar", "Interpretacja geometryczna wektora", "Długość (norma) wektora",
    "Iloczyn skalarny wektorów", "Kąt między wektorami", "Ortogonalność wektorów", "Iloczyn wektorowy", "Iloczyn mieszany",
    "Prosta w przestrzeni R^2 i R^3", "Płaszczyzna w przestrzeni R^3", "Wzajemne położenie prostych i płaszczyzn", "Odległość punktu od prostej i płaszczyzny", "Pojęcie macierzy",
    "Wymiar i rodzaje macierzy", "Dodawanie i odejmowanie macierzy", "Mnożenie macierzy przez skalar", "Mnożenie macierzy", "Transpozycja macierzy",
    "Macierz symetryczna i antysymetryczna", "Macierz tożsamościowa (jednostkowa)", "Wyznacznik macierzy 2x2", "Wyznacznik macierzy 3x3 (reguła Sarrusa)", "Minory i dopełnienia algebraiczne",
    "Rozwinięcie Laplace'a", "Własności wyznaczników", "Macierz odwrotna - definicja", "Wyznaczanie macierzy odwrotnej metodą dopełnień", "Rząd macierzy",
    "Układy równań liniowych", "Postać macierzowa układu równań", "Twierdzenie Kroneckera-Capellego", "Wzory Cramera", "Operacje elementarne na wierszach",
    "Metoda eliminacji Gaussa", "Metoda Gaussa-Jordana", "Przestrzeń wektorowa (liniowa)", "Podprzestrzeń wektorowa", "Kombinacja liniowa wektorów",
    "Liniowa niezależność wektorów", "Baza przestrzeni wektorowej", "Wymiar przestrzeni wektorowej", "Współrzędne wektora w bazie", "Zmiana bazy",
    "Macierz przejścia z bazy do bazy", "Przestrzeń euklidesowa", "Baza ortogonalna i ortonormalna", "Proces ortogonalizacji Grama-Schmidta", "Rzut ortogonalny wektora na podprzestrzeń",
    "Odwzorowania liniowe", "Jądro odwzorowania (Ker)", "Obraz odwzorowania (Im)", "Twierdzenie o rzędzie i zerowości", "Macierz odwzorowania liniowego",
    "Składanie odwzorowań liniowych", "Izomorfizm przestrzeni wektorowych", "Wartości własne macierzy", "Wektory własne macierzy", "Równanie charakterystyczne",
    "Wielomian charakterystyczny", "Przestrzeń własna", "Krotność algebraiczna i geometryczna", "Diagonalizacja macierzy", "Macierze podobne",
    "Potęgowanie macierzy diagonalizowalnych", "Twierdzenie Cayleya-Hamiltona", "Formy dwuliniowe", "Macierz formy dwuliniowej", "Formy kwadratowe",
    "Sprowadzanie form kwadratowych do postaci kanonicznej", "Metoda Lagrange'a diagonalizacji form", "Określoność form kwadratowych", "Kryterium Sylvestera", "Przestrzenie unitarne (zespolone)",
    "Nierówność Cauchy'ego-Schwarza", "Nierówność trójkąta dla normy", "Macierze ortogonalne", "Macierze unitarne", "Macierze hermitowskie",
    "Twierdzenie spektralne dla macierzy symetrycznych", "Rozkład spektralny", "Rozkład LU macierzy", "Rozkład Cholesky'ego", "Rozkład QR",
    "Singular Value Decomposition (SVD) - koncepcja", "Rozkład SVD w praktyce", "Pseudoodwrotność Moore'a-Penrose'a", "Zastosowanie SVD w kompresji obrazu", "Analiza Głównych Składowych (PCA) - podstawa algebraiczna",
    "Tensory i notacja indeksowa", "Iloczyn tensorowy przestrzeni", "Dekompozycja tensorowa (CP, Tucker)", "Macierze stochastyczne i łańcuchy Markowa", "Algebraiczne fundamenty algorytmu PageRank",
    "Funkcje macierzowe (eksponenta macierzy)", "Rozwiązywanie układów równań różniczkowych z e^At", "Algorytm Simplex (perspektywa algebry)", "Grupy Liego i algebry Liego", "Zastosowanie algebry w teorii reprezentacji i kognitywistyce"
  ],
  "Statystyka opisowa": [
    "Pojęcie populacji statystycznej i próby", "Jednostka i cecha statystyczna", "Klasyfikacja cech (ilościowe, jakościowe)", "Skale pomiarowe (nominalna, porządkowa, przedziałowa, stosunkowa)", "Metody gromadzenia danych",
    "Szereg statystyczny wyliczający", "Szereg rozdzielczy punktowy", "Szereg rozdzielczy przedziałowy", "Budowa przedziałów klasowych", "Rozpiętość przedziału klasowego",
    "Histogram i wielobok liczebności", "Dystrybuanta empiryczna (szereg skumulowany)", "Krzywa liczebności", "Miary położenia (przeciętne)", "Średnia arytmetyczna prosta",
    "Średnia arytmetyczna ważona", "Własności średniej arytmetycznej", "Średnia geometryczna (tempo zmian)", "Średnia harmoniczna", "Dominanta (moda) w szeregu prostym",
    "Dominanta w szeregu przedziałowym (interpolacja)", "Mediana (wartość środkowa)", "Kwantyle", "Kwartyl dolny (Q1) i górny (Q3)", "Decyle i percentyle",
    "Relacje między średnią, medianą a dominantą", "Miary zmienności (rozproszenia)", "Rozstęp (Range)", "Wariancja w populacji", "Wariancja z próby",
    "Odchylenie standardowe", "Własności wariancji i odchylenia", "Rozstęp ćwiartkowy (odchylenie ćwiartkowe)", "Odchylenie przeciętne", "Typowy obszar zmienności",
    "Współczynnik zmienności klasyczny", "Współczynnik zmienności pozycyjny", "Miary asymetrii (skośności)", "Moment centralny trzeciego rzędu", "Klasyczny współczynnik asymetrii (skośność)",
    "Pozycyjny współczynnik asymetrii", "Asymetria prawostronna i lewostronna", "Miary koncentracji", "Moment centralny czwartego rzędu", "Kurtoza (eksces)",
    "Rozkład platykurtyczny, mezokurtyczny i leptokurtyczny", "Wykres pudełkowy (Box plot)", "Identyfikacja wartości odstających (outliers)", "Reguła trzech sigm (reguła empiryczna)", "Standaryzacja wartości (Z-score)",
    "Analiza danych dwuwymiarowych", "Tablice kontyngencji (krzyżowe)", "Rozkłady brzegowe i warunkowe", "Kowariancja", "Wykres rozrzutu (Scatter plot)",
    "Współczynnik korelacji liniowej Pearsona", "Interpretacja współczynnika Pearsona", "Paradoks korelacji a przyczynowość (Spurious correlation)", "Regresja liniowa pierwszego rodzaju", "Metoda Najmniejszych Kwadratów (MNK)",
    "Współczynnik kierunkowy i wyraz wolny regresji", "Wariancja resztkowa", "Błąd standardowy szacunku", "Współczynnik determinacji R^2", "Współczynnik zbieżności phi^2",
    "Korelacja rang Spearmana", "Korelacja rang Kendalla", "Korelacja krzywoliniowa (stosunek korelacyjny)", "Miary zależności dla zmiennych nominalnych", "Współczynnik V Craméra",
    "Współczynnik kontyngencji C Pearsona", "Współczynnik T-Czuprowa", "Analiza dynamiki zjawisk", "Szeregi czasowe momentów i okresów", "Przyrosty absolutne jednopodstawowe i łańcuchowe",
    "Przyrosty względne", "Indeksy indywidualne jednopodstawowe", "Indeksy indywidualne łańcuchowe", "Zmiana podstawy indeksów", "Średnie tempo zmian zjawiska",
    "Indeksy agregatowe", "Indeks wartości", "Indeks cen Laspeyresa", "Indeks cen Paaschego", "Indeks ilości (wolumenu) Laspeyresa i Paaschego",
    "Indeks Fishera (idealny)", "Dekompozycja zmian wartości zjawiska", "Analiza szeregów czasowych", "Składowe szeregu czasowego (trend, sezonowość, cykl, wahania losowe)", "Wyrównywanie mechaniczne (średnie ruchome)",
    "Wyznaczanie trendu liniowego", "Modele addytywne i multiplikatywne sezonowości", "Wskaźniki sezonowości", "Wskaźniki demograficzne (stopa bezrobocia, wskaźniki obciążenia demograficznego)", "Krzywa koncentracji Lorentza",
    "Współczynnik Giniego w praktyce ekonomicznej", "Odległość euklidesowa w przestrzeni wielowymiarowej", "Metoda Taksonomii Wrocławskiej (syntetyczne mierniki rozwoju)", "Odległość Mahalanobisa w wykrywaniu anomalii", "Indeks Herfindahla-Hirschmana (HHI)"
  ],
  "Statystyka matematyczna": [
    "Przestrzeń zdarzeń elementarnych", "Zdarzenie losowe", "Klasyczna definicja prawdopodobieństwa", "Prawdopodobieństwo geometryczne", "Prawdopodobieństwo warunkowe",
    "Zdarzenia niezależne", "Wzór na prawdopodobieństwo całkowite", "Twierdzenie Bayesa", "Zmienna losowa jednowymiarowa", "Dystrybuanta zmiennej losowej",
    "Zmienna losowa dyskretna (skokowa)", "Funkcja prawdopodobieństwa (rozkład dyskretny)", "Zmienna losowa ciągła", "Funkcja gęstości prawdopodobieństwa", "Wartość oczekiwana zmiennej losowej",
    "Wariancja i odchylenie standardowe zmiennej losowej", "Momenty zwykłe i centralne", "Rozkład zero-jedynkowy i dwumianowy (Bernoulliego)", "Rozkład Poissona", "Rozkład hipergeometryczny",
    "Rozkład jednostajny ciagły", "Rozkład wykładniczy", "Rozkład normalny (Gaussa)", "Rozkład normalny standardowy N(0,1)", "Kwantyle rozkładów teoretycznych",
    "Prawo wielkich liczb (słabe i mocne)", "Centralne Twierdzenie Graniczne (Lindeberga-Lévy'ego)", "Próba losowa prosta", "Statystyka (jako zmienna losowa z próby)", "Rozkład średniej z próby",
    "Rozkład wariancji z próby", "Rozkład chi-kwadrat Pearsona", "Rozkład t-Studenta", "Rozkład F Snedecora", "Estymacja punktowa",
    "Własności estymatorów (nieobciążoność, zgodność, efektywność)", "Nierówność Rao-Craméra", "Metoda momentów w estymacji", "Metoda największej wiarygodności (MLE)", "Estymacja przedziałowa",
    "Przedział ufności dla średniej (wariancja znana)", "Przedział ufności dla średniej (wariancja nieznana, mała próba)", "Przedział ufności dla średniej (duża próba)", "Przedział ufności dla wariancji", "Przedział ufności dla frakcji (wskaźnika struktury)",
    "Określanie minimalnej wielkości próby", "Weryfikacja hipotez statystycznych", "Hipoteza zerowa i alternatywna", "Błąd pierwszego i drugiego rodzaju", "Poziom istotności testu",
    "Moc testu statystycznego", "Obszar krytyczny (zbiór odrzuceń)", "Prawdopodobieństwo testowe (p-value)", "Test dla wartości oczekiwanej (wariancja znana)", "Test dla wartości oczekiwanej (wariancja nieznana)",
    "Test dla wariancji", "Test dla wskaźnika struktury", "Testy dla dwóch średnich (próby niezależne)", "Test dla dwóch średnich (próby zależne/pary)", "Test dla dwóch wariancji",
    "Test dla dwóch frakcji", "Testy nieparametryczne - idea", "Test zgodności chi-kwadrat", "Test zgodności Kołmogorowa-Smirnowa", "Test normalności Shapiro-Wilka",
    "Test normalności Jarque-Bery", "Test niezależności chi-kwadrat", "Analiza wariancji (ANOVA) jednoczynnikowa", "Założenia testu ANOVA (homogeniczność, normalność)", "Test Levene'a dla homogeniczności wariancji",
    "Rozkład sumy kwadratów w ANOVA", "Testy post-hoc (Tukey, Scheffe)", "ANOVA dwuczynnikowa z interakcją", "Nieparametryczny test znaków", "Test Manna-Whitneya-Wilcoxona",
    "Test Wilcoxona dla par obserwacji", "Test Kruskala-Wallisa (nieparametryczny odpowiednik ANOVA)", "Estymacja klasycznego liniowego modelu regresji (KMRL)", "Założenia KMRL (Gaussa-Markowa)", "Własności estymatorów MNK (BLUE)",
    "Test t-Studenta dla istotności parametrów regresji", "Test F dla łącznej istotności modelu regresji", "Analiza reszt modelu regresji", "Heteroskedastyczność wariancji składnika losowego", "Testy Breuscha-Pagana i White'a",
    "Autokorelacja składnika losowego", "Test Durbina-Watsona", "Multikolinearność (współczynnik VIF)", "Rozkłady wielowymiarowe (wielowymiarowy rozkład normalny)", "Macierz kowariancji populacyjna i z próby",
    "Analiza czynnikowa (Factor Analysis) - podstawa matematyczna", "Test Mnożników Lagrange'a (LM test)", "Kryteria informacyjne (AIC, BIC) w doborze modeli", "Modele z ograniczoną zmienną objaśnianą (Logit, Probit)", "Analiza przeżycia (krzywe Kaplana-Meiera)",
    "Szeregi czasowe: testy pierwiastka jednostkowego (ADF)", "Kointegracja szeregów czasowych", "Statystyka bayesowska - prawdopodobieństwo a priori i a posteriori", "Zastosowanie twierdzenia Bayesa do zmiennych ciągłych", "Bayesowska estymacja punktowa",
    "Przedziały największej gęstości (HDI) w bayesianizmie", "Algorytmy MCMC (Markov Chain Monte Carlo)", "Metropolis-Hastings i Gibbs Sampler", "Metody resamplingowe (Bootstrap)", "Estymatory odporne i statystyka nienonparametryczna (robust statistics)"
  ]
});
Object.assign(window.KnowledgeTree, {
  "Ekonomia": [
    "Potrzeby i zasoby", "Rzadkość w ekonomii", "Koszt alternatywny", "Krzywa możliwości produkcyjnych", "Popyt rynkowy",
    "Prawo popytu", "Podaż rynkowa", "Prawo podaży", "Równowaga rynkowa", "Cena równowagi i mechanizm cenowy",
    "Elastyczność cenowa popytu", "Elastyczność dochodowa i mieszana popytu", "Elastyczność podaży", "Teoria użyteczności", "Krzywe obojętności",
    "Linia ograniczenia budżetowego", "Optimum konsumenta", "Funkcja produkcji", "Prawo malejących przychodów krańcowych", "Koszty stałe i zmienne",
    "Koszty przeciętne i krańcowe", "Zysk rachunkowy a zysk ekonomiczny", "Konkurencja doskonała", "Monopol i siła rynkowa", "Oligopol (modele Cournota, Bertranda)",
    "Konkurencja monopolistyczna", "Asymetria informacji (pokusa nadużycia, negatywna selekcja)", "Dobra publiczne", "Efekty zewnętrzne (eksternalia)", "Teoria gier (Dylemat więźnia)",
    "Podstawowe pojęcia makroekonomiczne", "Produkt Krajowy Brutto (PKB)", "Metody obliczania PKB (wydatkowa, dochodowa, produkcyjna)", "PKB nominalne a realne", "Deflator PKB",
    "Wzrost gospodarczy", "Cykl koniunkturalny", "Fazy cyklu koniunkturalnego", "Bezrobocie (frykcyjne, strukturalne, cykliczne)", "Prawo Okuna",
    "Inflacja i wskaźnik CPI", "Przyczyny i skutki inflacji", "Krzywa Phillipsa", "Pieniądz i jego funkcje", "Podaż pieniądza (agregaty M0, M1, M2, M3)",
    "System rezerwy cząstkowej i mnożnik kreacji pieniądza", "Bank Centralny", "Polityka monetarna (stopy procentowe, operacje otwartego rynku)", "Teoria ilościowa pieniądza", "Polityka fiskalna",
    "Budżet państwa", "Deficyt budżetowy i dług publiczny", "Efekt wypychania", "Popyt agregatowy (AD)", "Podaż agregatowa (AS)",
    "Model AD-AS", "Model IS-LM", "Funkcja konsumpcji i oszczędności (Keynes)", "Mnożnik keynesowski", "Bariery wzrostu gospodarczego",
    "Handel międzynarodowy", "Koszty komparatywne (Ricardo)", "Bilans płatniczy i bilans handlowy", "Kursy walutowe (sztywne, płynne)", "Parytet siły nabywczej (PPP)",
    "Teoria Heckshera-Ohlina", "Integracja gospodarcza", "Unia celna i strefa wolnego handlu", "Globalizacja", "Kapitał ludzki",
    "Ekonomia behawioralna", "Heurystyki i błędy poznawcze w decyzjach", "Teoria perspektywy (Kahneman, Tversky)", "Nudge (architektura wyboru)", "Ekonomia instytucjonalna",
    "Prawa własności (twierdzenie Coase'a)", "Ekonomia sektora publicznego", "Model Solowa (wzrost gospodarczy)", "Kapitał społeczny", "Ekonomia środowiska",
    "Handel uprawnieniami do emisji", "Nowa makroekonomia klasyczna", "Teoria racjonalnych oczekiwań", "Oczekiwania adaptacyjne", "Realne cykle koniunkturalne (RBC)",
    "Neokeynesizm", "Modele Równowagi Ogólnej (CGE)", "Ekonometria szeregów czasowych w ekonomii", "Modele wektorowej autoregresji (VAR)", "Ekonometria przestrzenna",
    "Modele dynamicznej stochastycznej równowagi ogólnej (DSGE)", "Gospodarka oparta na wiedzy", "Ekonomia cyrkularna", "Ekonomia złożoności (Complexity Economics)", "Modelowanie agentowe w ekonomii (ABM)"
  ],
  "Rachunkowość finansowa": [
    "Pojęcie i funkcje rachunkowości", "Podstawowe zasady rachunkowości", "Zasada podwójnego zapisu", "Majątek jednostki (Aktywa)", "Źródła finansowania majątku (Pasywa)",
    "Równanie bilansowe", "Konto księgowe i jego budowa", "Zasady funkcjonowania kont bilansowych", "Zestawienie obrotów i sald", "Dowody księgowe",
    "Dziennik i księga główna", "Księgi pomocnicze", "Rozrachunki", "Podatek VAT w rachunkowości", "Przychody ze sprzedaży",
    "Koszty układu rodzajowego", "Koszty w układzie kalkulacyjnym", "Ustalanie wyniku finansowego", "Wynik ze sprzedaży, z działalności operacyjnej, brutto, netto", "Konta wynikowe",
    "Rozliczenia międzyokresowe kosztów (czynne i bierne)", "Rozliczenia międzyokresowe przychodów", "Środki trwałe (definicja, klasyfikacja)", "Wartość początkowa środków trwałych", "Amortyzacja i umorzenie środków trwałych",
    "Metody amortyzacji (liniowa, degresywna, naturalna)", "Zbycie i likwidacja środków trwałych", "Wartości niematerialne i prawne", "Inwestycje długoterminowe", "Zapasy (materiały, towary, produkcja w toku, wyroby gotowe)",
    "Metody wyceny rozchodu zapasów (FIFO, LIFO, AVCO)", "Inwentaryzacja", "Różnice inwentaryzacyjne (niedobory i nadwyżki)", "Należności i zobowiązania", "Odpisy aktualizujące wartość należności",
    "Środki pieniężne w kasie i na rachunkach", "Krótkoterminowe papiery wartościowe", "Kapitał (fundusz) podstawowy", "Kapitał zapasowy i rezerwowy", "Zobowiązania wekslowe",
    "Kredyty i pożyczki bankowe", "Rezerwy na zobowiązania", "Rozliczenia z tytułu wynagrodzeń", "Rozliczenia publicznoprawne (ZUS, US)", "Podatek dochodowy od osób prawnych (CIT)",
    "Podatek odroczony (aktywa i rezerwy)", "Sprawozdanie finansowe - składniki", "Bilans (układ i treść)", "Rachunek zysków i strat (wariant kalkulacyjny i porównawczy)", "Rachunek przepływów pieniężnych (Cash Flow)",
    "Metoda bezpośrednia i pośrednia Cash Flow", "Zestawienie zmian w kapitale własnym", "Informacja dodatkowa do sprawozdania finansowego", "Polityka rachunkowości", "Zdarzenia po dniu bilansowym",
    "Błędy z lat ubiegłych", "Krajowe Standardy Rachunkowości (KSR)", "Międzynarodowe Standardy Rachunkowości (MSR / MSSF)", "Różnice między Ustawą o Rachunkowości a MSSF", "Leasing operacyjny i finansowy (MSSF 16)",
    "Wycena instrumentów finansowych (MSSF 9)", "Utrata wartości aktywów (MSR 36)", "Rozpoznawanie przychodów z umów z klientami (MSSF 15)", "Kontrakty długoterminowe", "Rachunkowość zabezpieczeń (Hedge accounting)",
    "Różnice kursowe", "Działalność zaniechana (MSSF 5)", "Połączenia jednostek gospodarczych (MSSF 3)", "Wartość firmy (Goodwill) i jej utrata wartości", "Konsolidacja sprawozdań finansowych",
    "Metoda pełna, proporcjonalna i praw własności w konsolidacji", "Podmioty powiązane", "Zasady sporządzania raportów zintegrowanych (ESG)", "Sprawozdawczość niefinansowa", "XBRL - elektroniczne raportowanie finansowe",
    "Rachunkowość zarządcza a finansowa", "Kalkulacja podziałowa", "Kalkulacja doliczeniowa", "Rachunek kosztów zmiennych", "Próg rentowności (Break-Even Point)",
    "Rachunek kosztów działań (ABC)", "Budżetowanie", "Odchylenia od kosztów standardowych", "Centra odpowiedzialności (zysku, kosztów, inwestycji)", "Rachunkowość kreatywna i oszustwa księgowe",
    "Audyt i badanie sprawozdań finansowych", "Niezależność biegłego rewidenta", "Opinia z badania sprawozdania", "Analiza fundamentalna na bazie sprawozdań", "Automatyzacja procesów księgowych (RPA)"
  ],
  "Rynki finansowe": [
    "Pojęcie i funkcje rynku finansowego", "Uczestnicy rynku finansowego", "Podział rynków finansowych", "Rynek pieniężny", "Instrumenty rynku pieniężnego (bony skarbowe, lokaty)",
    "Rynek kapitałowy", "Giełda Papierów Wartościowych", "Rynek pierwotny a wtórny", "Emisja papierów wartościowych (IPO)", "Prospekt emisyjny",
    "Papiery wartościowe", "Akcje (zwykłe, uprzywilejowane)", "Prawa z akcji", "Dywidenda i dzień odcięcia dywidendy", "Prawa poboru",
    "Obligacje", "Obligacje skarbowe, korporacyjne, komunalne", "Cena nominalna i cena emisyjna obligacji", "Kupon obligacji (oprocentowanie stałe i zmienne)", "Rentowność obligacji do terminu zapadalności (YTM)",
    "Ryzyko stopy procentowej", "Czas trwania obligacji (Duration)", "Wypukłość obligacji (Convexity)", "Ocena wiarygodności kredytowej (Ratingi)", "Agencje ratingowe",
    "Rynek walutowy (Forex)", "Pary walutowe", "Kurs krzyżowy", "Bid, Ask i Spread", "Ryzyko walutowe",
    "Indeksy giełdowe (np. WIG20, S&P 500)", "Metodologie budowy indeksów", "Rynek zorganizowany a rynek OTC", "Animator rynku (Market Maker)", "Zlecenia giełdowe (PKC, PCR, limit ceny)",
    "Krótka sprzedaż (Short selling)", "Depozyt zabezpieczający (Margin)", "Instytucje infrastruktury rynku (KDPW, Izby Rozliczeniowe)", "Towarzystwa Funduszy Inwestycyjnych (TFI)", "Fundusze otwarte (FIO) i zamknięte (FIZ)",
    "Fundusze ETF", "Fundusze emerytalne", "Fundusze Venture Capital i Private Equity", "Instrumenty pochodne (Derywaty) - wprowadzenie", "Kontrakty Forward",
    "Kontrakty Futures", "Różnice między Forward a Futures", "Opcje finansowe", "Opcje Call i Put", "Premia opcyjna i cena wykonania (Strike)",
    "Profil wypłaty z opcji", "Wewnętrzna wartość opcji a wartość czasowa", "Zabezpieczanie się przed ryzykiem (Hedging)", "Spekulacja na rynkach pochodnych", "Arbitraż",
    "Swapy", "Swapy stóp procentowych (IRS)", "Swapy walutowe (CIRS)", "Swapy ryzyka kredytowego (CDS)", "Wycena kontraktów Forward",
    "Drzewa dwumianowe w wycenie opcji", "Model Blacka-Scholesa-Mertona", "Współczynniki greckie (Delta, Gamma, Theta, Vega, Rho)", "Opcje egzotyczne", "Produkty strukturyzowane",
    "Sekurytyzacja aktywów", "MBS i CDO (papiery oparte na hipotekach)", "Teoria Błądzenia Losowego", "Hipoteza Rynku Efektywnego (Fama)", "Finanse behawioralne na rynkach",
    "Anomalie rynkowe (efekt stycznia, momentum)", "Zarządzanie portfelem (teoria Markowitza)", "Granica efektywna portfela", "Model CAPM", "Model APT (Arbitrage Pricing Theory)",
    "Mierniki oceny portfela (Sharpe, Treynor, Jensen)", "Ryzyko systematyczne i niesystematyczne", "Value at Risk (VaR)", "Expected Shortfall (CVaR)", "Zarządzanie ryzykiem rynkowym",
    "Kryptowaluty", "Technologia Blockchain w finansach", "Tokenizacja aktywów", "DeFi (Decentralized Finance)", "Algorytmiczny handel na giełdzie (Algo trading)",
    "High-Frequency Trading (HFT)", "Dark Pools", "Regulacje rynków finansowych (MiFID II)", "Bazylea III / IV (dla banków)", "Modele stochastyczne w finansach (Heston, SABR)"
  ],
  "Wycena spółek (Corporate Finance)": [
    "Wartość pieniądza w czasie (TVM)", "Wartość przyszła (FV)", "Wartość obecna (PV)", "Renta kapitałowa (zwykła i z góry)", "Renta wieczna",
    "Efektywna roczna stopa procentowa", "Stopa dyskontowa", "Ryzyko i stopa zwrotu", "Koszt kapitału własnego", "Koszt kapitału obcego",
    "Średni ważony koszt kapitału (WACC)", "Struktura kapitału", "Teoria Modiglianiego-Millera (bez podatków)", "Teoria Modiglianiego-Millera (z podatkami)", "Koszty trudności finansowych",
    "Teoria agencji", "Polityka dywidendowa", "Budżetowanie kapitałowe (ocena projektów inwestycyjnych)", "Wartość zaktualizowana netto (NPV)", "Wewnętrzna stopa zwrotu (IRR)",
    "Zmodyfikowana wewnętrzna stopa zwrotu (MIRR)", "Okres zwrotu (zwykły i zdyskontowany)", "Indeks zyskowności (PI)", "Problemy z IRR dla nietypowych przepływów", "Ocena projektów o różnym czasie trwania (EAA)",
    "Podejścia do wyceny przedsiębiorstw", "Wycena majątkowa", "Metoda wartości księgowej i skorygowanej", "Metoda wartości likwidacyjnej i odtworzeniowej", "Wycena dochodowa",
    "Wolne przepływy pieniężne dla firmy (FCFF)", "Wolne przepływy pieniężne dla właścicieli (FCFE)", "Dyskonto FCFF (wycena wartości firmy - EV)", "Dyskonto FCFE (wycena wartości kapitałów własnych)", "Prognozowanie przychodów i kosztów",
    "Prognozowanie nakładów inwestycyjnych i kapitału obrotowego", "Wartość rezydualna", "Model Gordona", "Wycena porównawcza (mnożnikowa)", "Mnożniki kapitałowe (P/E, P/BV)",
    "Mnożniki wartości przedsiębiorstwa (EV/EBITDA, EV/EBIT)", "Wybór spółek porównywalnych (Peer group)", "Premie i dyskonta w wycenie", "Premia za kontrolę", "Dyskonto za brak płynności",
    "Wycena opcji realnych", "Metoda Skorygowanej Wartości Obecnej (APV)", "Ekonomiczna Wartość Dodana (EVA)", "Rynkowa Wartość Dodana (MVA)", "Fuzje i przejęcia (M&A) - motywy",
    "Synergie w M&A", "Wycena synergii", "Przejęcia lewarowane (LBO)", "Modelowanie finansowe (LBO model)", "Zarządzanie kapitałem obrotowym netto",
    "Zarządzanie należnościami i zapasami", "Zarządzanie gotówką (model Baumola)", "Finansowanie krótkoterminowe", "Finansowanie długoterminowe", "Leasing a kredyt (analiza opłacalności)",
    "Emisja obligacji korporacyjnych", "Finansowanie hybrydowe (obligacje zamienne, akcje uprzywilejowane)", "Polityka wypłat dla akcjonariuszy (dywidendy vs. skup akcji)", "Skup akcji własnych (Buyback)", "Analiza wskaźnikowa",
    "Wskaźniki płynności", "Wskaźniki zadłużenia", "Wskaźniki aktywności (rotacji)", "Wskaźniki rentowności (ROE, ROA, ROS)", "Analiza Du Ponta",
    "Dźwignia operacyjna (DOL)", "Dźwignia finansowa (DFL)", "Dźwignia całkowita (DTL)", "Zarządzanie ryzykiem finansowym w przedsiębiorstwie", "Model Altmana (Z-score)",
    "Restrukturyzacja finansowa", "Opcje strategiczne przedsiębiorstwa", "Wycena startupów", "Metoda Venture Capital", "Metoda Berkus'a / Scorecard",
    "Koszt kapitału dla rynków wschodzących", "Wycena firm w kryzysie", "Due Diligence finansowe", "Rachunkowość zabezpieczeń z perspektywy wyceny", "Modelowanie stochastyczne w CF (Monte Carlo)"
  ]
});
Object.assign(window.KnowledgeTree, {
  "Python (Pandas/Numpy)": [
    "Zmienne i typy danych", "Operatory arytmetyczne i logiczne", "Instrukcje warunkowe (if, elif, else)", "Pętle (for, while)", "Listy i krotki (tuples)",
    "Słowniki (dictionaries) i zbiory (sets)", "Definiowanie funkcji (def)", "Argumenty pozycyjne i nazwane", "Zasięg zmiennych", "Moduły i pakiety",
    "List comprehensions", "Funkcje lambda", "Map, filter, reduce", "Obsługa wyjątków (try, except)", "Operacje na plikach",
    "Klasy i obiekty (OOP)", "Dziedziczenie i polimorfizm", "Wirtualne środowiska (venv)", "Instalacja pakietów (pip)", "Podstawy Jupyter Notebook",
    "Wprowadzenie do NumPy", "Tablice ndarray", "Tworzenie tablic (zeros, ones, arange)", "Typy danych w NumPy", "Indeksowanie i wycinanie (slicing) tablic",
    "Operacje arytmetyczne na tablicach", "Broadcasting w NumPy", "Funkcje uniwersalne (ufuncs)", "Agregacje w NumPy (sum, mean, max)", "Logiczne indeksowanie",
    "Sortowanie i unikalne elementy", "Operacje macierzowe i algebra liniowa w NumPy (np.linalg)", "Generowanie liczb pseudolosowych (np.random)", "Zapis i odczyt tablic", "Wprowadzenie do Pandas",
    "Obiekty Series", "Obiekty DataFrame", "Tworzenie DataFrame z list i słowników", "Wczytywanie danych (read_csv, read_excel)", "Podgląd danych (head, tail, info, describe)",
    "Indeksowanie (loc, iloc)", "Filtrowanie i selekcja warunkowa", "Dodawanie i usuwanie kolumn", "Zmiana nazw kolumn i indeksów", "Modyfikacja danych i apply()",
    "Obsługa braków danych (dropna, fillna)", "Identyfikacja i usuwanie duplikatów", "Grupowanie danych (groupby)", "Agregacja wielokrotna (agg)", "Tabele przestawne (pivot_table)",
    "Przekształcanie danych (melt)", "Łączenie tabel (merge, join)", "Konkatenacja danych (concat)", "Zarządzanie czasem w Pandas (DatetimeIndex)", "Resampling i przesunięcia czasowe (shift)",
    "Okna kroczące (rolling)", "Metody tekstowe (str.contains, str.extract)", "Kategorie (Categorical data)", "Zaawansowane indeksowanie (MultiIndex)", "Optymalizacja typów danych dla oszczędności pamięci",
    "Web scraping (BeautifulSoup, requests)", "Praca z API (JSON)", "Wyrażenia regularne (re)", "Łączenie z bazami danych (SQLAlchemy)", "Wprowadzenie do wizualizacji (Matplotlib)",
    "Podstawowe wykresy (plot, scatter, bar)", "Dostosowywanie wykresów w Matplotlib", "Subploty", "Biblioteka Seaborn", "Wykresy rozkładów w Seaborn (histplot, kdeplot)",
    "Wykresy korelacji (heatmap, pairplot)", "Wykresy kategoryczne (boxplot, violinplot)", "Interaktywne wykresy (Plotly)", "Tworzenie dashboardów (Streamlit, Dash)", "Wstęp do uczenia maszynowego (Scikit-learn)",
    "Przetwarzanie wstępne danych (StandardScaler, OneHotEncoder)", "Podział na zbiór treningowy i testowy", "Regresja liniowa w Scikit-learn", "Drzewa decyzyjne i Lasy losowe", "Walidacja krzyżowa (Cross-validation)",
    "Wyszukiwanie hiperparametrów (GridSearchCV)", "Analiza tekstów (NLTK, spaCy)", "Głębokie uczenie (TensorFlow/Keras lub PyTorch) - koncepcja", "Dekoratory i generatory w Pythonie", "Metaklasy i zaawansowane OOP",
    "Profilowanie kodu (cProfile)", "Wektoryzacja na poziomie C i unikanie pętli", "Biblioteka Numba (JIT compilation)", "Cython (łączenie Pythona z C)", "Przetwarzanie równoległe (multiprocessing)",
    "Przetwarzanie asynchroniczne (asyncio)", "Rozproszone przetwarzanie (Dask)", "Rozproszone DataFrame (PySpark)", "Zarządzanie zależnościami (Poetry)", "Testowanie kodu (pytest, mock)"
  ],
  "Bazy Danych (SQL)": [
    "Pojęcie bazy danych i DBMS", "Relacyjny model danych", "Tabele, wiersze i kolumny", "Typy danych w SQL", "Klucz główny (Primary Key)",
    "Klucz obcy (Foreign Key)", "Relacje (1:1, 1:N, N:M)", "Normalizacja (1NF, 2NF, 3NF)", "Język SQL - DDL, DML, DQL, DCL", "Instrukcja SELECT",
    "Filtrowanie danych (WHERE)", "Operatory porównania", "Operatory logiczne (AND, OR, NOT)", "Operator IN i BETWEEN", "Wyszukiwanie wzorców (LIKE)",
    "Sortowanie wyników (ORDER BY)", "Limitowanie wyników (LIMIT, TOP)", "Aliasy kolumn i tabel (AS)", "Funkcje skalarne (np. UPPER, LOWER, ROUND)", "Operacje na datach i czasie",
    "Instrukcje warunkowe (CASE WHEN)", "Wartości NULL w bazie", "Operator IS NULL", "Funkcja COALESCE (lub ISNULL/NVL)", "Złączenia tabel - wprowadzenie",
    "INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN", "CROSS JOIN",
    "Złączenia własne (SELF JOIN)", "Operatory zbiorowe (UNION, UNION ALL)", "INTERSECT i EXCEPT (MINUS)", "Funkcje agregujące (COUNT, SUM, AVG, MIN, MAX)", "Grupowanie danych (GROUP BY)",
    "Filtrowanie grup (HAVING)", "Kolejność wykonywania zapytań logicznych", "Podzapytania (Subqueries)", "Podzapytania skorelowane", "Operatory EXISTS i ANY/ALL",
    "Wspólne wyrażenia tablicowe (CTE - WITH)", "Rekurencyjne CTE", "Funkcje okna (Window Functions)", "Partycjonowanie i sortowanie w oknie (PARTITION BY, ORDER BY)", "Funkcje rankujące (ROW_NUMBER, RANK, DENSE_RANK)",
    "Funkcje przesunięcia (LAG, LEAD)", "Dodawanie danych (INSERT)", "Modyfikacja danych (UPDATE)", "Usuwanie danych (DELETE, TRUNCATE)", "Tworzenie tabel (CREATE TABLE)",
    "Modyfikacja struktury tabeli (ALTER TABLE)", "Usuwanie tabel (DROP TABLE)", "Ograniczenia integralnościowe (Constraints)", "Widoki (Views)", "Widoki zmaterializowane",
    "Indeksy (Clustered, Non-clustered)", "Jak działają indeksy (drzewa B-Tree)", "Projektowanie wydajnych zapytań", "Plany wykonania zapytania (Execution Plans)", "SARGability (wyszukiwalność argumentów)",
    "Unikanie funkcji na kolumnach w klauzuli WHERE", "Transakcje (BEGIN, COMMIT, ROLLBACK)", "Właściwości ACID", "Poziomy izolacji transakcji", "Blokady i zakleszczenia (Deadlocks)",
    "Procedury składowane (Stored Procedures)", "Funkcje zdefiniowane przez użytkownika (UDF)", "Wyzwalacze (Triggers)", "Zmienne i pętle w SQL (np. w T-SQL lub PL/SQL)", "Obsługa błędów (TRY...CATCH)",
    "Tymczasowe tabele (#, ##)", "Zmienne tablicowe", "Dynamiczny SQL (EXEC, sp_executesql)", "Partycjonowanie tabel", "Indeksy kolumnowe (Columnstore Indexes)",
    "Optymalizacja dużych tabel", "Architektura hurtowni danych (Gwiazda, Płatek śniegu)", "Tabele faktów i wymiarów", "Zwolno zmieniające się wymiary (SCD)", "Ekstrakcja, Transformacja, Ładowanie (ETL vs ELT)",
    "Przetwarzanie JSON w SQL", "Przetwarzanie danych przestrzennych (Spatial data)", "NoSQL vs SQL (kluczowe różnice)", "Graph Databases (wstęp)", "Modelowanie danych obiektowo-relacyjnych",
    "SQL Injection i bezpieczeństwo", "Zarządzanie uprawnieniami (GRANT, REVOKE)", "Kopie zapasowe i odtwarzanie bazy", "Replikacja i klastrowanie", "Nowoczesne silniki SQL w chmurze (Snowflake, BigQuery, Redshift)"
  ],
  "Power BI / R": [
    "Wprowadzenie do Business Intelligence", "Różnica między Power BI Desktop a Service", "Pobieranie danych w Power BI (Get Data)", "Interfejs Power Query", "Typy danych w Power Query",
    "Usuwanie i zmiana nazwy kolumn", "Filtrowanie i sortowanie wierszy", "Zastępowanie wartości", "Wypełnianie braków (Fill Down/Up)", "Dzielenie i łączenie kolumn",
    "Przekształcanie kolumn na wiersze (Unpivot)", "Grupowanie w Power Query", "Dołączanie zapytań (Append)", "Scalanie zapytań (Merge)", "Wprowadzenie do języka M (Power Query Formula Language)",
    "Model danych (Data Model)", "Tabele faktów i wymiarów", "Klucze podstawowe i obce", "Tworzenie relacji w modelu", "Kierunek filtrowania krzyżowego (Cross-filter direction)",
    "Aktywne i nieaktywne relacje", "Ukrywanie pól dla użytkowników raportu", "Wprowadzenie do DAX (Data Analysis Expressions)", "Kolumny obliczeniowe a Miary (Measures)", "Funkcje agregujące w DAX (SUM, MIN, MAX)",
    "Kontekst filtru i kontekst wiersza", "Funkcja CALCULATE", "Filtrowanie w CALCULATE (FILTER, ALL, ALLEXCEPT)", "Funkcja RELATED i RELATEDTABLE", "Funkcje iteracyjne (SUMX, AVERAGEX)",
    "Funkcje logiczne (IF, SWITCH)", "Time Intelligence (inteligencja czasowa)", "Tabela kalendarza (Date table)", "Funkcje DATESYTD, DATESMTD", "Funkcje SAMEPERIODLASTYEAR, DATEADD",
    "Tworzenie wizualizacji w Power BI", "Wykresy kolumnowe i słupkowe", "Wykresy liniowe i warstwowe", "Wykresy kołowe i pierścieniowe (najlepsze praktyki)", "Karty i wskaźniki (KPI)",
    "Tabele i macierze (Matrix)", "Drzewo dekompozycji i Q&A", "Filtry i fragmentatory (Slicers)", "Zarządzanie interakcjami wizualnymi", "Zastosowanie zakładek (Bookmarks)",
    "Tworzenie przycisków i nawigacji", "Dynamiczne tytuły i formatowanie warunkowe", "Formatowanie narzędzi (Tooltips)", "Zarządzanie rolami (RLS - Row Level Security)", "Publikacja raportów do usługi Power BI",
    "Obszary robocze (Workspaces)", "Pulpity nawigacyjne (Dashboards)", "Odświeżanie danych (Scheduled Refresh)", "Bramy danych (Data Gateways)", "Udostępnianie raportów (Apps)",
    "Wprowadzenie do języka R", "Zmienne, wektory i macierze w R", "Czynniki (Factors)", "Ramki danych (Data Frames) i listy", "Podstawowe pakiety (Base R)",
    "Wprowadzenie do dplyr", "Filtrowanie (filter), selekcja (select)", "Transformacje (mutate), podsumowania (summarise)", "Operator strumieniowy (pipe: %>% lub |>)", "Przekształcanie danych (tidyr)",
    "Wizualizacja z pakietem ggplot2", "Geometrie w ggplot2 (geom_point, geom_line)", "Mapowanie estetyk (aes)", "Fasetowanie (facet_wrap, facet_grid)", "Zaawansowane motywy (themes) w ggplot2",
    "Integracja R z Power BI", "Pobieranie danych w Power BI za pomocą skryptów R", "Transformacje danych z użyciem R w Power Query", "Tworzenie wizualizacji R (R Visuals) w Power BI", "Modele statystyczne (lm) w R",
    "Modelowanie szeregów czasowych (forecast, prophet) w R i integracja z PBI", "Uczenie maszynowe (caret, tidymodels)", "Wdrażanie ML z R do Power BI", "Optymalizacja wydajności modeli DAX", "Narzędzia analityczne (DAX Studio, Tabular Editor)",
    "Kalkulacyjne grupy w Tabular Editor", "XMLA Endpoints", "Parametry typu What-If", "Funkcje DAX manipulujące relacjami (USERELATIONSHIP)", "Kontekst zmiennych (VAR, RETURN)",
    "Optymalizacja silnika VertiPaq", "Aplikacje R Shiny - wprowadzenie", "Zarządzanie cyklem życia (ALM) w Power BI", "Power BI Premium", "Zarządzanie architekturą Microsoft Fabric"
  ],
  "Excel Zaawansowany": [
    "Interfejs i nawigacja w arkuszu", "Adresowanie względne, bezwzględne i mieszane", "Skróty klawiszowe zwiększające produktywność", "Typy danych (liczby, teksty, daty)", "Formatowanie niestandardowe liczb",
    "Ochrona arkuszy i skoroszytów", "Sprawdzanie poprawności danych (Data Validation)", "Listy rozwijane", "Dynamiczne listy rozwijane", "Formatowanie warunkowe",
    "Formuły w formatowaniu warunkowym", "Funkcje tekstowe (LEWY, PRAWY, FRAGMENT.TEKSTU)", "ZŁĄCZ.TEKSTY i operator &", "ZNAJDŹ i SZUKAJ.TEKST", "Funkcje czasowe (DZIŚ, TERAZ, DATA.RÓŻNICA)",
    "Funkcje logiczne (JEŻELI, LUB, ORAZ)", "Zagnieżdżone funkcje JEŻELI i WARUNKI", "Funkcje agregujące z warunkami (SUMA.JEŻELI, LICZ.JEŻELI)", "SUMA.WARUNKÓW, LICZ.WARUNKI", "Wyszukiwanie danych (WYSZUKAJ.PIONOWO)",
    "Ograniczenia WYSZUKAJ.PIONOWO i błędy (#N/D!)", "WYSZUKAJ.POZIOMO", "PODAJ.POZYCJĘ i INDEKS", "Nowa funkcja X.WYSZUKAJ (XLOOKUP)", "Obsługa błędów (JEŻELI.BŁĄD)",
    "Tabele Excela (Ctrl+T)", "Referencje strukturalne w Tabelach", "Sortowanie wielopoziomowe", "Filtrowanie i filtry zaawansowane", "Sumy częściowe",
    "Tabele przestawne (Pivot Tables)", "Pola obliczeniowe i elementy obliczeniowe w Tabeli Przestawnej", "Grupowanie w tabeli przestawnej (daty, wartości)", "Slicery (Fragmentatory) i Oś czasu", "Wykresy przestawne",
    "Analiza danych za pomocą wykresów (dobór wykresów)", "Wykresy kombi (oś pomocnicza)", "Wykresy wodospadowe (Waterfall)", "Wykresy przebiegu w czasie (Sparklines)", "Dynamiczne wykresy",
    "Narzędzia Analizy (Szukaj wyniku, Tabela danych)", "Menedżer scenariuszy", "Dodatek Solver", "Funkcje finansowe (PMT, PV, FV)", "Funkcje tablicowe (wstęp)",
    "Dynamiczne tablice (Dynamic Arrays)", "Funkcje UNIKALNE, SORTUJ, SORTUJ.WEDŁUG", "Funkcje FILTRUJ, SEKWENCJA, MACIERZ.LOS", "Konsolidacja danych", "Narzędzie Tekst jako kolumny",
    "Audyt formuł (Śledzenie zależności)", "Wstęp do Power Query w Excelu", "Import z różnych źródeł (CSV, Web, Folder)", "Czyszczenie danych w Power Query", "Łączenie zapytań (Merge & Append)",
    "Język M (podstawy)", "Wstęp do Power Pivot", "Model danych w Excelu", "Relacje w Power Pivot", "Wstęp do DAX (Kalkulacje i Miary w Excelu)",
    "Makrodefinicje (Rejestrowanie makr)", "Bezpieczeństwo makr", "Wprowadzenie do VBA (Visual Basic for Applications)", "Edytor VBA (VBE) i moduły", "Obiekt, Metoda, Właściwość w VBA",
    "Zmienne i typy danych w VBA", "Okna dialogowe (MsgBox, InputBox)", "Pętle w VBA (For...Next, Do...While)", "Instrukcje warunkowe (If...Then...Else, Select Case)", "Praca z zakresem i komórkami (Range, Cells)",
    "Kolekcje (Workbooks, Worksheets)", "Zdarzenia w VBA (Events)", "Obsługa błędów w VBA (On Error)", "Optymalizacja kodu VBA (Application.ScreenUpdating)", "Tablice w VBA",
    "Komunikacja Excela z Wordem/Outlookiem przez VBA", "Użytkownicze Formularze (UserForms)", "Automatyzacja raportów od A do Z", "Office Scripts (TypeScript) w Excel Online", "Office Scripts vs VBA",
    "Automatyzacja przy użyciu Power Automate z Excelem", "Web Scraping przy użyciu Excela (Power Query / VBA)", "Optymalizacja ciężkich skoroszytów (Memory management)", "Excel jako aplikacja - najlepsze praktyki architektoniczne", "Tworzenie zaawansowanych dashboardów z użyciem VBA i Power Pivot"
  ]
});
Object.assign(window.KnowledgeTree, {
  "Angielski (Biznesowy)": [
    "Przedstawianie się w kontekście zawodowym", "Podstawowe słownictwo biurowe", "Zasady pisania e-maili (formal / informal)", "Umawianie i odwoływanie spotkań", "Alfabet i literowanie (spelling)",
    "Rozmowy telefoniczne (podstawowe zwroty)", "Opisywanie rutyny i obowiązków w pracy", "Przedstawianie firmy i jej produktów", "Słownictwo z zakresu obsługi klienta", "Zgłaszanie problemów i reklamacji",
    "Podstawowe pojęcia finansowe po angielsku (invoice, receipt)", "Raportowanie postępów w projekcie", "Wyrażanie opinii na spotkaniach", "Zgadzanie się i brak zgody (polite disagreement)", "Skróty biznesowe (ASAP, FYI, EOD)",
    "Słownictwo HR (rekrutacja, CV, rozmowa kwalifikacyjna)", "Proponowanie rozwiązań i burza mózgów", "Rozmowy kurtuazyjne (Small talk)", "Organizacja agendy spotkania", "Słownictwo z zakresu IT (podstawy dla biznesu)",
    "Pytania pośrednie (Indirect questions) dla zachowania uprzejmości", "Słownictwo działu marketingu (target market, campaign)", "Strona bierna w raportach (The report was prepared)", "Zarządzanie projektami w języku angielskim (milestones, deliverables)", "Dyskusja o trendach i zmianach (rośnie, maleje)",
    "Interpretacja wykresów (pie chart, bar chart)", "Prezentacje biznesowe: powitanie i zarys struktury", "Przechodzenie między slajdami (Signposting)", "Skupianie uwagi słuchaczy", "Odpowiadanie na trudne pytania z widowni",
    "Podkreślanie znaczenia i parafrazowanie", "Zarządzanie czasem podczas prezentacji po angielsku", "Negocjacje: ustalanie celów i ram", "Składanie i przyjmowanie ofert", "Techniki kompromisu w negocjacjach (Trade-offs)",
    "Odrzucanie ofert w sposób dyplomatyczny", "Zamknięcie negocjacji i podsumowanie ustaleń", "Różnice kulturowe w komunikacji biznesowej (Cross-cultural communication)", "Korespondencja formalna (listy intencyjne, zapytania ofertowe)", "Protokół spotkania (Minutes of the meeting)",
    "Zarządzanie kryzysowe po angielsku (PR crisis)", "Zaawansowane słownictwo analityczne (correlation, causation, variance)", "Analiza SWOT po angielsku", "Słownictwo związane z logistyką i łańcuchem dostaw (supply chain)", "Przedstawianie wyników finansowych spółki",
    "Terminologia księgowa (assets, liabilities, equity)", "Terminologia podatkowa (tax avoidance vs tax evasion)", "Umowy i kontrakty (legal jargon: herein, aforementioned)", "Klauzule poufności (NDA)", "Terminologia giełdowa (bull market, bear market)",
    "Słownictwo z zakresu Corporate Finance (WACC, NPV)", "Dyskusje o strategiach rynkowych (M&A, joint venture)", "Inwestycje i wycena (due diligence)", "Startup ecosystem (pitching, venture capital, seed round)", "Język przywództwa (Leadership and management)",
    "Dawanie i odbieranie feedbacku po angielsku", "Zarządzanie zmianą (Change management terminology)", "Wywieranie wpływu i perswazja", "Język dyplomacji na najwyższym szczeblu", "Konwencje networkingowe (Elevator pitch)",
    "Angielski w audycie finansowym (materiality, audit trail)", "Terminologia z zakresu Data Science i analityki Big Data", "Terminologia rynków walutowych i derywatów", "Opisywanie modeli ekonometrycznych i statystycznych", "Angielski prawniczy w finansach (Compliance, AML)",
    "Pisanie White Papers i raportów branżowych", "Analizy makroekonomiczne po angielsku (QE, interest rates)", "Rozmowy o ryzyku i zarzadzaniu portfelem inwestycyjnym", "Opisywanie architektury baz danych i systemów BI", "Język korporacyjnych sprawozdań rocznych (Annual Reports)",
    "Odczytywanie i interpretacja prospektów emisyjnych po angielsku", "Terminologia ESG (Environmental, Social, Governance)", "Słownictwo z zakresu cyberbezpieczeństwa w instytucjach finansowych", "Język fuzji i przejęć (Hostile takeover, poison pill)", "Terminologia LBO (Leveraged Buyouts) i Private Equity",
    "Tworzenie Term Sheets w języku angielskim", "Rozmowy z akcjonariuszami i zarządem (Board meeting language)", "Złożona składnia w dokumentach prawno-finansowych", "Idiomy biznesowe najwyższego szczebla (C-level idioms)", "Zaawansowana wymowa (Business accent reduction)"
  ],
  "Prezentacja Danych": [
    "Wprowadzenie do wizualizacji danych", "Rozumienie odbiorcy (Audience first)", "Cel wizualizacji: eksploracyjna vs perswazyjna", "Rodzaje zmiennych i dobór wykresu", "Wykresy kolumnowe a słupkowe",
    "Kiedy stosować wykresy kołowe (i dlaczego rzadko)", "Wykresy liniowe do pokazywania trendów", "Wykresy punktowe (scatter plot) a korelacja", "Zasada atramentu danych (Data-ink ratio Tuftego)", "Usuwanie zbędnych elementów (Chartjunk)",
    "Wykorzystanie przestrzeni pozytywowej i negatywowej", "Psychologia kolorów w prezentacji danych", "Kolory sekwencyjne, rozbieżne i kategoryczne", "Używanie szarości dla kontekstu", "Zwracanie uwagi kolorem (Highlighting)",
    "Dostępność (Accessibility) w doborze kolorów (np. daltonizm)", "Typografia w dashboardach i raportach", "Hierarchia wizualna", "Pre-attentive processing (przetwarzanie przeduwagowe)", "Zasady Gestalt (bliskość, podobieństwo, domknięcie)",
    "Prowadzenie wzroku odbiorcy (wzór Z i F)", "Dobór osi: czy oś Y zawsze musi zaczynać się od zera?", "Logarytmiczna skala osi", "Etykiety danych zamiast legendy", "Zarządzanie gęstością danych",
    "Wykresy wodospadowe (Waterfall) w finansach", "Wykresy pociskowe (Bullet graphs) dla KPI", "Wykresy pudełkowe (Box-plots) dla rozkładów", "Wykresy skrzypcowe (Violin plots)", "Mapy cieplne (Heatmaps)",
    "Wykresy bąbelkowe", "Wykresy radarowe (Pajęczynowe) - wady i zalety", "Wykresy lejkowe (Funnel charts) w marketingu", "Mapy drzewa (Treemaps)", "Wykresy Sankeya do przepływów",
    "Mapy kartograficzne (Choropleth maps)", "Wykresy kaskadowe i Marimekko", "Projektowanie dashboardów", "Różnica między raportem, prezentacją a dashboardem", "Wireframing dashboardu",
    "Umiejscowienie kluczowych informacji (Zasada górnego lewego rogu)", "5-sekundowy test dashboardu", "Nawigacja w dashboardach interaktywnych", "Drill-down i drill-through", "Filtrowanie i interakcje",
    "Tooltipy jako dodatkowy wymiar danych", "Responsywność raportów (Mobile BI)", "Data Storytelling - koncepcja", "Bohater, konflikt i rozwiązanie w danych", "Zasada 3 aktów w prezentacji analitycznej",
    "Kontekstualizacja danych (Benchmarki)", "Storyboarding analityczny", "Adnotacje na wykresach (Etykiety narracyjne)", "Wizualizacja niepewności (Przedziały ufności, Fan charts)", "Wizualizacja symulacji Monte Carlo",
    "Zasady tworzenia prezentacji (slajdów) biznesowych", "Zasada oddechu (White space) na slajdzie", "Slajdy wizualne vs tekstowe (Zasada 10/20/30)", "Prezentowanie na żywo a raport do czytania (Slideument)", "Animacje i przejścia (kiedy stosować)",
    "Budowanie zaufania przez przejrzystość danych", "Kłamanie statystyką (jak unikać pułapek manipulacji)", "Zarządzanie obciążeniem poznawczym (Cognitive load)", "Testowanie użyteczności dashboardów (A/B testing)", "Zastosowanie SVG do niestandardowych wizualizacji",
    "D3.js i zaawansowane biblioteki JS (wstęp)", "Gramatyka grafiki (Leland Wilkinson)", "Algorytmiczne generowanie sztuki z danych (Generative art)", "Design Systems w analityce wizualnej", "Infografiki analityczne"
  ],
  "Kognitywistyka / ADHD": [
    "Definicja i zakres kognitywistyki", "Budowa układu nerwowego", "Kora przedczołowa a funkcje wykonawcze", "Neuroprzekaźniki (dopamina, noradrenalina, serotonina)", "Uwaga skierowana i mimowolna",
    "Rodzaje pamięci (krótkotrwała, długotrwała, operacyjna)", "Proces konsolidacji pamięci", "Percepcja a interpretacja rzeczywistości", "Mechanizmy uczenia się", "Warunkowanie klasyczne i sprawcze",
    "Plastyczność mózgu (Neuroplastyczność)", "Sen i jego rola w uczeniu się", "Odpoczynek i Default Mode Network (DMN)", "Stres a funkcje poznawcze", "Wpływ kortyzolu na hipokamp",
    "Definicja ADHD wg klasyfikacji ICD/DSM", "ADHD jako zaburzenie neurorozwojowe", "Zaburzenia funkcji wykonawczych", "Rola układu dopaminergicznego w ADHD", "Rola układu noradrenergicznego",
    "Nadpobudliwość psychoruchowa", "Deficyty uwagi a uwaga hiper-fokusowana (Hyperfocus)", "Impulsywność w działaniu i decyzjach", "Rozregulowanie emocjonalne w ADHD", "Ślepota na czas (Time blindness)",
    "Pamięć robocza u osób z ADHD", "Prokrastynacja jako problem z regulacją emocji", "Bariera rozpoczęcia zadania (Task initiation deficit)", "Przeciążenie sensoryczne", "Przebodźcowanie",
    "Zjawisko RSD (Rejection Sensitive Dysphoria)", "Dysonans poznawczy", "Heurystyki w procesach decyzyjnych", "Obciążenie poznawcze (Cognitive Load Theory)", "Teoria podwójnego kodowania (Paivio)",
    "Zasada Zeigarnik i efekt Owsiankiny", "Diagnoza ADHD u dorosłych", "Komorbidność (współwystępowanie m.in. z lękiem, depresją)", "ADHD a spektrum autyzmu (AuDHD)", "Mechanizmy kompensacyjne",
    "Farmakoterapia w ADHD (stymulanty i niestymulanty)", "Mechanizm działania metylofenidatu", "Terapia poznawczo-behawioralna (CBT) w ADHD", "Mindfulness (uważność) jako trening uwagi", "Techniki zakotwiczania w teraźniejszości",
    "Body doubling (praca z partnerem u boku)", "Zewnętrzne strukturyzowanie środowiska", "Zarządzanie dopaminą", "Detoks dopaminowy (mity i fakty)", "Zasada małych nagród",
    "Tworzenie sztucznych terminów (Fake deadlines)", "Fidgeting i uwalnianie napięcia ruchowego", "Gamifikacja procesów nauki", "Wizualizacja czasu (np. Time Timer)", "Rutyny a elastyczność poznawcza",
    "Zarządzanie energią vs zarządzanie czasem", "Efekt hiper-fokusu - zalety i zagrożenia", "Pętla nawyku (sygnał, rutyna, nagroda)", "Złota zasada zmiany nawyku", "Tarcie behawioralne (Zmniejszanie barier wejścia)",
    "Podejmowanie decyzji pod wpływem emocji", "Regulacja systemu nerwowego (nerw błędny)", "Biofeedback i Neurofeedback", "Ćwiczenia fizyczne a neurogeneza (BDNF)", "Wpływ diety na funkcje poznawcze (oś jelita-mózg)",
    "Rozwój metapoznania (Metacognition)", "Samoświadomość w kryzysach motywacyjnych", "Systemy wspierające pamięć zewnętrzną", "Interfejsy mózg-komputer (BCI) - wstęp", "Kognitywna ergonomia pracy analitycznej",
    "Optymalizacja stanowiska pracy pod kątem sensorycznym", "Teoria systemów dynamicznych w rozwoju", "Neuromodulacja (np. tDCS, rTMS)", "Złożone modele interwencji behawioralnej", "Farmakologia zaawansowana (interakcje lekowe w psychiatrii)"
  ],
  "Zarządzanie czasem": [
    "Świadomość czasu a jego percepcja", "Rejestrowanie czasu (Time tracking)", "Identyfikacja pożeraczy czasu", "Zasada Pareto (80/20) w produktywności", "Prawo Parkinsona (Praca wypełnia czas)",
    "Ustalanie priorytetów", "Macierz Eisenhowera (Ważne/Pilne)", "Zasada 2 minut (GTD)", "Metoda ABCDE", "Eat that Frog (Zjedz tę żabę - B. Tracy)",
    "Zarządzanie zadaniami", "To-do list (Lista zadań)", "Pułapki list zadań", "Metoda MoSCoW", "Systemy zarządzania produktywnością",
    "GTD (Getting Things Done) - Kolekcjonowanie", "GTD - Przetwarzanie i Organizacja", "GTD - Przegląd tygodniowy", "Zarządzanie projektami osobistymi", "Planowanie zwinne (Agile/Scrum na co dzień)",
    "Kanban osobisty (Trello)", "Limity WIP (Work In Progress)", "Timeboxing (Blokowanie czasu w kalendarzu)", "Zasada Batchingu (Grupowanie zadań podobnych)", "Praca w cyklach (Metoda Pomodoro)",
    "Modyfikacje Pomodoro i zarządzanie energią", "Przerwy i ich rola w utrzymaniu skupienia", "Zarządzanie kalendarzem", "Zasada jednej platformy", "Harmonogramowanie zadań cyklicznych",
    "Cele długoterminowe", "Metoda SMART(ER)", "Cele oparte na wartościach", "Systemy OKR (Objectives and Key Results)", "Planowanie 12-tygodniowego roku (12 Week Year)",
    "Budowanie nawyków produktywnych", "Metoda atomowych nawyków (J. Clear)", "Gromadzenie nawyków (Habit stacking)", "Śledzenie nawyków (Habit tracking)", "Minimalizm informacyjny",
    "Zarządzanie powiadomieniami i rozpraszaczami", "Skrzynka odbiorcza Zero (Inbox Zero)", "Zarządzanie komunikacją e-mail", "Zarządzanie spotkaniami (efektywna agenda)", "Zarządzanie delegowaniem zadań",
    "Zasada asertywności w produktywności (Sztuka mówienia NIE)", "Zarządzanie wiedzą osobistą (PKM)", "Drugi Mózg (Building a Second Brain - T. Forte)", "Zettelkasten (metoda Luhmanna)", "Zarządzanie plikami i folderami (Metoda PARA)",
    "Zarządzanie notatkami (Obsidian, Notion)", "Praca głęboka (Deep Work - Cal Newport)", "Płycizna informacyjna (Shallow Work)", "Architektura środowiska pracy głębokiej", "Dopasowanie zadań do chronotypu",
    "Poranna i wieczorna rutyna", "Planowanie Dnia Następnego", "Odraczanie gratyfikacji", "Prokrastynacja strategiczna", "Narzędzia automatyzacji osobistej",
    "Zapier i Make (wstęp do no-code)", "Automatyzacja procesów z e-mailem", "Automatyczne przypomnienia i skrypty", "Reguły wyzwalaczy (If This Then That)", "Zarządzanie kontekstem (Context switching costs)",
    "Efektywne czytanie (Speed reading i skanowanie)", "Metoda Cornell do notowania", "Sztuczna inteligencja w zarządzaniu czasem (AI assistants)", "Audyt produktywności", "Iteracyjna poprawa procesów własnych",
    "Kaizen (ciągłe doskonalenie w czasie)", "Odporność psychiczna a produktywność", "Zapobieganie wypaleniu zawodowemu", "Zrównoważenie życia zawodowego i prywatnego (Work-life integration)", "Skrajna optymalizacja (Hyper-efficiency) i jej zagrożenia"
  ]
});
