window.KnowledgeTree = window.KnowledgeTree || {};
Object.assign(window.KnowledgeTree, {
  "VBA": [
    "Nagrywanie i edycja makr", "Moduły i zmienne (Dim, Set)", "Pętle (For, Do While) i Warunki", "Manipulacja arkuszem z kodu (Cells, Range)", "Tworzenie własnych funkcji (UDF)", "User Forms i zaawansowane skrypty automatyzujące"
  ],
  "R (Język programowania)": [
    "Składnia bazowa i operacje na wektorach", "Ramki danych (Data Frames) i dplyr", "Czyszczenie i transformacja danych", "Zaawansowana wizualizacja z pakietem ggplot2", "Analiza statystyczna i modele regresji liniowej w R", "Szeregi czasowe i prognozowanie ekonomiczne"
  ],
  "Finanse Osobiste i Rynki": [
    "Budżetowanie domowe", "Zarządzanie przepływami pieniężnymi", "Zasady oszczędzania", "Fundusz awaryjny", "Konta oszczędnościowe i lokaty", "Wartość pieniądza w czasie (TVM)", "Procent składany", "Zrozumienie i wpływ inflacji", "Zarządzanie długiem konsumenckim", "Karty kredytowe i scoring BIK",
    "Kredyt hipoteczny podstawy", "Koszty okołokredytowe (RRSO)", "Konsolidacja zadłużenia", "Podstawy systemu podatkowego", "Ulgi i odliczenia podatkowe", "Optymalizacja podatkowa osobista", "Emerytura państwowa a prywatna", "IKE i IKZE", "PPE i PPK", "Ubezpieczenia na życie",
    "Ubezpieczenia majątkowe i zdrowotne", "Zarządzanie ryzykiem osobistym", "Niezależność finansowa (FIRE)", "Podstawy rynków finansowych", "Czym są akcje i udziały", "Obligacje skarbowe", "Obligacje korporacyjne", "Fundusze inwestycyjne (FIO)", "Fundusze ETF podstawy", "Dobór ETFów do portfela",
    "Inwestowanie w złoto i srebro", "Nieruchomości pod wynajem (REITs)", "Podstawy kryptowalut", "Bitcoin i Ethereum", "Dywersyfikacja portfela", "Korelacja aktywów", "Profil ryzyka inwestora", "Horyzont inwestycyjny", "Strategia Buy and Hold", "Dollar Cost Averaging (DCA)",
    "Rebalancing portfela", "Finanse behawioralne", "Błędy poznawcze w inwestowaniu", "FOMO i FUD rynkowy", "Analiza fundamentalna podstawy", "Czytanie sprawozdań finansowych", "Wskaźniki P/E i P/BV", "ROE i ROA spółek", "Analiza techniczna wstęp", "Wykresy świecowe",
    "Trend rynkowy i wsparcia", "Średnie kroczące (SMA/EMA)", "Wskaźniki momentum (RSI)", "MACD i oscylatory", "Formacje cenowe", "Inwestowanie w wartość (Value)", "Inwestowanie we wzrost (Growth)", "Inwestowanie dywidendowe", "Arystokraci dywidendowi", "Podatki od zysków kapitałowych",
    "Derywaty podstawy", "Opcje (Call i Put)", "Kontrakty terminowe (Futures)", "Rynek walutowy (Forex)", "Dźwignia finansowa (Margin)", "Ryzyko walutowe inwestycji", "Analiza makroekonomiczna", "Cykle koniunkturalne", "Polityka banków centralnych", "Stopy procentowe a giełda",
    "Wskaźniki wyprzedzające (PMI/CPI)", "Platformy maklerskie", "Koszty transakcyjne i prowizje", "Robo-doradcy", "Inwestowanie społecznościowe", "Alternatywne aktywa (Sztuka)", "Rynki wschodzące (Emerging)", "Megatrendy inwestycyjne", "Inwestowanie ESG", "Zabezpieczanie portfela (Hedging)",
    "Arbitraż podstawy", "Bezpieczeństwo środków i KNF", "Gwarancje bankowe (BFG)", "Prawo spadkowe i sukcesja", "Testamenty i fundacje rodzinne", "Optymalizacja kosztów życia", "Minimalizm finansowy", "Arbitraż geograficzny", "Negocjacje finansowe", "Analiza ryzyka utraty pracy",
    "Ekonomia współdzielenia", "Kredyty walutowe ryzyka", "Ochrona przed oszustwami (SCAM)", "Piramidy finansowe (Ponzi)", "Cyfrowe bezpieczeństwo portfeli", "Budowanie zdolności kredytowej", "Wycena start-upów", "Inwestowanie na rynku niepublicznym", "Zarządzanie majątkiem HNWI", "Venture Capital dla początkujących"
  ],
  "Finanse Korporacyjne i Quant": [
    "Cele finansowe przedsiębiorstwa", "Maksymalizacja wartości dla akcjonariuszy", "Rola CFO w korporacji", "Sprawozdawczość finansowa", "Analiza bilansu", "Rachunek zysków i strat", "Rachunek przepływów pieniężnych (Cash Flow)", "Wskaźniki płynności finansowej", "Zarządzanie kapitałem obrotowym", "Cykl konwersji gotówki",
    "Zarządzanie należnościami", "Finansowanie krótkoterminowe", "Kredyt kupiecki", "Faktoring i forfaiting", "Planowanie finansowe", "Budżetowanie operacyjne", "Prognozowanie Pro Forma", "Analiza progu rentowności (BEP)", "Dźwignia operacyjna", "Dźwignia finansowa",
    "Dźwignia całkowita", "Koszt długu", "Koszt kapitału własnego", "Model CAPM w wycenie", "Średni ważony koszt kapitału (WACC)", "Struktura kapitału", "Teoria Modiglianiego-Millera", "Koszty bankructwa", "Teoria Pecking Order", "Budżetowanie kapitałowe (Capital Budgeting)",
    "Wartość bieżąca netto (NPV)", "Wewnętrzna stopa zwrotu (IRR)", "Zmodyfikowana IRR (MIRR)", "Okres zwrotu (Payback Period)", "Indeks zyskowności (PI)", "Ryzyko w ocenie projektów", "Analiza scenariuszy i wrażliwości", "Drzewa decyzyjne w inwestycjach", "Opcje realne (Real Options)", "Polityka dywidendowa",
    "Skup akcji własnych (Buyback)", "Emisja akcji (IPO)", "Emisja obligacji korporacyjnych", "Leasing operacyjny i finansowy", "Kredyty konsorcjalne", "Mezzanine finance", "Fuzje i Przejęcia (M&A) wstęp", "Synergie kosztowe i przychodowe", "Wycena celów przejęć (Mnożniki)", "Wycena modelem DCF",
    "Leveraged Buyout (LBO)", "Management Buyout (MBO)", "Obrona przed wrogim przejęciem", "Due Diligence finansowe", "Restrukturyzacja zadłużenia", "Prawo upadłościowe korporacji", "Nadzór korporacyjny (Corporate Governance)", "Wynagrodzenia menedżerów a opcje", "Konflikty agencji", "Zarządzanie ryzykiem walutowym",
    "Hedging korporacyjny", "Swapy stóp procentowych (IRS)", "Forwardy i opcje walutowe", "Podatki w korporacji", "Ceny transferowe", "Finansowanie projektów (Project Finance)", "Partnerstwo Publiczno-Prywatne (PPP)", "Spółki celowe (SPV)", "Standardy rachunkowości (IFRS/GAAP)", "Audyt finansowy",
    "Wstęp do Quant Finance", "Analiza szeregów czasowych", "Modelowanie stochastyczne w finansach", "Proces Wienera", "Lemat Ito", "Wycena opcji model Black-Scholes", "Współczynniki Greckie (Delta)", "Współczynniki Greckie (Gamma, Theta)", "Implikowana zmienność (Implied Volatility)", "Model drzewa dwumianowego",
    "Monte Carlo w finansach", "Wycena instrumentów egzotycznych", "Value at Risk (VaR)", "Conditional VaR (Expected Shortfall)", "Stress testing portfela", "Ryzyko kredytowe modeli", "Modele scoringowe (Altman Z-score)", "Credit Default Swaps (CDS)", "Ryzyko płynności", "Handel algorytmiczny (Algorithmic Trading)",
    "Strategie Mean-Reversion", "Strategie Trend-Following", "Arbitraż statystyczny", "High-Frequency Trading (HFT)", "Mikrostruktura rynku", "Order Book dynamics", "Dark Pools", "Machine Learning w finansach", "Przetwarzanie języka naturalnego w tradingu", "Analiza alternatywnych danych (Alt Data)"
  ],
  "Zarządzanie Projektami (Agile)": [
    "Wprowadzenie do metodyk zwinnych", "Manifest Agile", "4 Wartości Agile", "12 Zasad Agile", "Trójkąt ograniczeń w Agile", "Kultura zwinna organizacji", "Różnice między Agile a Waterfall", "Cykl życia projektu zwinnego", "Zarządzanie wartością (Value-driven delivery)", "Empiryzm (Inspekcja, Adaptacja)",
    "Wprowadzenie do Scrum", "Role w Scrum", "Odpowiedzialności Scrum Mastera", "Odpowiedzialności Product Ownera", "Rola Deweloperów", "Cechy samoorganizującego się zespołu", "Wydarzenia w Scrum", "Sprint jako serce Scruma", "Sprint Planning (Planowanie)", "Cel Sprintu (Sprint Goal)",
    "Daily Scrum (Codzienny Scrum)", "Sprint Review (Przegląd)", "Sprint Retrospective (Retrospekcja)", "Artefakty w Scrum", "Product Backlog", "Sprint Backlog", "Przyrost (Increment)", "Definicja Ukończenia (Definition of Done)", "Definicja Gotowości (Definition of Ready)", "Zarządzanie wymaganiami",
    "Epiki (Epics)", "Historyjki użytkownika (User Stories)", "Kryteria Akceptacji", "Reguła INVEST w historyjkach", "Persony projektowe", "Refinement (Pielęgnacja) Backlogu", "Metody estymacji zwinnej", "Story Points i miary względne", "Planning Poker", "T-shirt sizing",
    "Prędkość zespołu (Velocity)", "Wykres spalania (Burndown Chart)", "Wykres wypalania (Burnup Chart)", "Wprowadzenie do Kanban", "Tablica Kanban", "Limity WIP (Work In Progress)", "Prawo Little'a", "Zarządzanie przepływem pracy", "Czas realizacji (Lead Time)", "Czas cyklu (Cycle Time)",
    "Wykres CFD (Cumulative Flow Diagram)", "Klasy Usług w Kanban", "Scrumban (Scrum + Kanban)", "Extreme Programming (XP) wstęp", "Programowanie w parach (Pair Programming)", "Test-Driven Development (TDD) w XP", "Ciągła Integracja (CI)", "Ciągłe Dostarczanie (CD)", "Wspólna własność kodu", "Refaktoryzacja",
    "Proste projektowanie (KISS w XP)", "Skalowanie Agile", "Ramy SAFe (Scaled Agile Framework)", "Agile Release Train (ART)", "Release Train Engineer (RTE)", "Planowanie PI (Program Increment)", "LeSS (Large-Scale Scrum)", "Nexus Framework", "Scrum@Scale", "Agile PMO",
    "Zwinne kontraktowanie", "Zarządzanie interesariuszami w Agile", "Rozwiązywanie konfliktów w zespole", "Komunikacja w zespołach rozproszonych", "Facylitacja spotkań", "Agile Coaching", "Modele dojrzałości Agile", "OKR (Objectives and Key Results)", "Zwinne budżetowanie", "Narzędzia: Jira Software",
    "Narzędzia: Confluence", "Narzędzia: Trello i Asana", "Mapy drogowe (Roadmaps)", "Planowanie wydań (Release Planning)", "Metryki zwinne (Agile Metrics)", "Design Thinking a Agile", "Lean Startup", "Tworzenie MVP (Minimum Viable Product)", "Pivotowanie projektu", "Pętle zwrotne (Feedback Loops)",
    "Ciągłe doskonalenie (Kaizen)", "Zarządzanie ryzykiem zwinnym", "Psychologiczne bezpieczeństwo zespołu", "Antywzorce w Scrumie (Scrum But)", "Zarządzanie długiem technicznym", "Skuteczne demo produktu", "Estymacja NoEstimates", "Zarządzanie wypaleniem w zespole", "Zwinny HR", "Ewolucja zwinnego przywództwa"
  ],
  "Zarządzanie Projektami (PMP)": [
    "Czym jest projekt wg PMI", "Cykl życia projektu a cykl życia produktu", "Struktury organizacyjne (Matrycowa, Projektowa)", "Rola Kierownika Projektu", "Trójkąt ograniczeń (Zakres, Czas, Koszt)", "PMO (Project Management Office)", "Kodeks etyki PMI", "5 Grup Procesów (Inicjowanie, Planowanie)", "5 Grup Procesów (Realizacja, Zamykanie)", "10 Obszarów Wiedzy PMBOK",
    "Opracowanie Karty Projektu (Project Charter)", "Opracowanie Planu Zarządzania Projektem", "Kierowanie i zarządzanie pracą", "Zarządzanie wiedzą w projekcie", "Monitorowanie prac projektu", "Zintegrowana kontrola zmian (Change Request)", "Zamykanie projektu lub fazy", "Planowanie zarządzania zakresem", "Gromadzenie wymagań", "Definiowanie zakresu",
    "Tworzenie struktury podziału pracy (WBS)", "Weryfikacja zakresu", "Kontrola zakresu", "Planowanie zarządzania harmonogramem", "Definiowanie działań", "Ustalanie sekwencji działań", "Szacowanie czasu trwania", "Metoda Ścieżki Krytycznej (CPM)", "Metoda Łańcucha Krytycznego (CCM)", "Wykresy Gantta i sieciowe",
    "Opracowanie harmonogramu", "Kompresja harmonogramu (Crashing, Fast Tracking)", "Kontrola harmonogramu", "Planowanie zarządzania kosztami", "Szacowanie kosztów (Analogiczne, Parametryczne)", "Szacowanie PERT", "Opracowanie budżetu", "Zarządzanie wartością wypracowaną (EVM)", "Wskaźniki CV, SV, CPI, SPI", "Prognozowanie EAC, ETC, TCPI",
    "Kontrola kosztów", "Planowanie zarządzania jakością", "Koszt jakości (CoQ)", "Zarządzanie jakością (QA)", "Kontrola jakości (QC)", "Narzędzia jakości (Diagramy Ishikawy, Pareto)", "Planowanie zarządzania zasobami", "Szacowanie zasobów działań", "Pozyskiwanie zasobów", "Rozwój zespołu (Fazy Tuckmana)",
    "Zarządzanie zespołem i konflikty", "Style przywództwa", "Teorie motywacji (Maslow, McGregor)", "Kontrola zasobów", "Planowanie zarządzania komunikacją", "Określanie kanałów komunikacji", "Zarządzanie komunikacją", "Monitorowanie komunikacji", "Planowanie zarządzania ryzykiem", "Identyfikacja ryzyk (Rejestr Ryzyk)",
    "Jakościowa analiza ryzyka", "Ilościowa analiza ryzyka (Monte Carlo, EMV)", "Planowanie reakcji na szanse", "Planowanie reakcji na zagrożenia", "Wdrażanie reakcji na ryzyko", "Monitorowanie ryzyka", "Planowanie zarządzania zamówieniami", "Typy kontraktów (Fixed Price, CR, T&M)", "Przeprowadzanie zamówień", "Kontrola zamówień",
    "Identyfikacja interesariuszy", "Macierz Władza/Zainteresowanie", "Planowanie zaangażowania interesariuszy", "Zarządzanie zaangażowaniem interesariuszy", "Monitorowanie zaangażowania interesariuszy", "Otoczenie biznesowe projektu", "Wymagania zgodności i regulacje (Compliance)", "Zarządzanie zmianą organizacyjną", "Realizacja korzyści biznesowych", "Analiza środowiska (PESTLE)",
    "Audyty projektowe", "Dokumentacja Lessons Learned", "Przejście do utrzymania (Handover)", "Złożoność i niejednoznaczność projektów (VUCA)", "Metodyki hybrydowe (PMP + Agile)", "Dopasowywanie metodyki (Tailoring)", "Inteligencja emocjonalna w projektach", "Zastosowanie analizy danych w projektach", "Myślenie systemowe (Systems Thinking)", "Rozwiązywanie problemów",
    "Przywództwo służebne (Servant Leadership)", "Rozwój kompetencji analitycznych PM-a", "Techniki facylitacji PMP", "Praktyki zrównoważonego rozwoju (Sustainability)", "Zarządzanie wartością wypracowaną na sterydach", "Mapowanie strumienia wartości", "Design of Experiments (DoE)", "Analiza Make-or-Buy", "Inspekcje i Walkthrough", "Rozliczanie kontraktów"
  ],
  "Kognitywistyka i Neurobiologia": [
    "Wprowadzenie do kognitywistyki", "Filozofia umysłu podst", "Problem umysł-ciało (Mind-Body Problem)", "Dualizm vs Monizm", "Behawioryzm w psychologii", "Rewolucja kognitywna", "Funkcjonalizm w filozofii umysłu", "Sztuczna Inteligencja a poznanie (Test Turinga)", "Chiński Pokój (Argument Searle'a)", "Konektywizm i sieci neuronowe",
    "Reprezentacje umysłowe", "Obliczeniowa teoria umysłu (CTM)", "Zarządzanie uwagą i percepcją", "Teorie percepcji wizualnej (Gestalt)", "Złudzenia optyczne i przetwarzanie dół-góra/góra-dół", "Pamięć sensoryczna i krótkotrwała", "Pamięć operacyjna (Model Baddeleya)", "Pamięć epizodyczna vs semantyczna", "Zapominanie i interferencja", "Procesy uczenia się (Warunkowanie)",
    "Neuroplastyczność umysłu", "Myślenie i rozwiązywanie problemów", "Heurystyki i błędy poznawcze (Kahneman)", "Teoria perspektywy", "Rozumowanie dedukcyjne i indukcyjne", "Rozwój poznawczy (Teoria Piageta)", "Akwizycja języka (Chomsky)", "Hipoteza Sapira-Whorfa", "Semantyka i pragmatyka języka", "Mózgowe mechanizmy mowy (Ośrodek Broki)",
    "Trudny problem świadomości (Chalmers)", "Teorie świadomości (Global Workspace Theory)", "Emocje i procesy poznawcze", "Teoria uczuć i emocji", "Inteligencja: teorie i pomiar", "Kognitywistyka ewolucyjna", "Psychologia ewolucyjna", "Poznanie u zwierząt", "Poznanie społeczne", "Teoria Umysłu (Theory of Mind)",
    "Empatia i neurony lustrzane", "Poznanie ucieleśnione (Embodied cognition)", "Rozszerzony umysł (Extended mind)", "Neurobiologiczne podstawy uwagi", "Mechanizmy nagrody (Dopamina)", "Podejmowanie decyzji (Neuroekonomia)", "Percepcja czasu przez mózg", "Mózg a muzyka", "Psychofizyka (Prawo Webera-Fechnera)", "Sztucczne systemy poznawcze",
    "Oko i kora wzrokowa", "Rozpoznawanie twarzy i prozopagnozja", "Agnazje percepcyjne", "Ślepota na zmiany (Change blindness)", "Ślepota z nieuwagi (Inattentional blindness)", "Syndrom pomijania stronnego", "Sen i marzenia senne a pamięć", "Wpływ stresu na poznanie", "Przetwarzanie informacji wielomodalnej", "Koncepcje jaźni (Self)",
    "Zaburzenia poznawcze: Autyzm i Spektrum", "Zaburzenia poznawcze: Schizofrenia", "Zaburzenia poznawcze: Alzheimer i demencje", "Interfejsy mózg-komputer (BCI)", "Neuroetyka", "Ulepszanie poznawcze (Nootropiki)", "Sztuczna świadomość (Zagrożenia i szanse)", "Przetwarzanie predykcyjne (Predictive processing)", "Teoria wolnej energii Fristona", "Fenomenologia umysłu",
    "Intencjonalność stanów umysłowych", "Qualia i argumenty wiedzy", "Kognitywistyka matematyki", "Moralność a mózg", "Neuroestetyka", "Modelowanie matematyczne procesów poznawczych", "Architektury kognitywne (ACT-R, SOAR)", "Teorie działania i kontrola motoryczna", "Afektywna neuronauka", "Neuromarketing",
    "Rola snu w konsolidacji wspomnień", "Metakognicja", "Wirtualna rzeczywistość w badaniach umysłu", "Interakcja człowiek-komputer (HCI)", "UX Design a psychologia poznawcza", "Neuroedukacja", "Plastyczność kompensacyjna po uszkodzeniach", "Zależność poznania od kultury", "Epistemologia kognitywna", "Świadomość zwierząt wyższych",
    "Zdolności poznawcze ptaków (Krukowate)", "Sztuczna wąska inteligencja (ANI) a ludzki mózg", "Różnice indywidualne w stylach poznawczych", "Czynnik genetyczny w zdolnościach poznawczych", "Starzenie się układu poznawczego", "Trening poznawczy (Brain training)", "Przyszłość kognitywistyki (Hybrydy)", "Symulowanie umysłu (Whole brain emulation)", "Synestezja", "Stany zmienionej świadomości (OOBE, NDE)"
  ],
  "Matematyka (Algebra i Analiza)": [
    "Logika zdaniowa", "Rachunek kwantyfikatorów", "Metody dowodzenia (wprost, nie wprost)", "Indukcja matematyczna", "Teoria mnogości - podstawy", "Relacje i funkcje (Injekcja, Surjekcja)", "Zbiory przeliczalne i nieprzeliczalne", "Liczby rzeczywiste i zespolone", "Zasada szufladkowa Dirichleta", "Podstawy algebry liniowej",
    "Wektory i przestrzeń wektorowa", "Kombinacja liniowa wektorów", "Niezależność liniowa", "Baza i wymiar przestrzeni wektorowej", "Macierze - definicje", "Dodawanie i mnożenie macierzy", "Transpozycja macierzy", "Wyznacznik macierzy", "Macierz odwrotna", "Rząd macierzy",
    "Układy równań liniowych", "Twierdzenie Kroneckera-Capellego", "Metoda Gaussa", "Wzory Cramera", "Odwzorowania liniowe", "Jądro i obraz odwzorowania (Kernel, Image)", "Przestrzenie Euklidesowe", "Ortogonalność wektorów", "Proces ortogonalizacji Grama-Schmidta", "Wartości i wektory własne",
    "Wielomian charakterystyczny", "Diagonalizacja macierzy", "Formy kwadratowe", "Rozkład SVD wstęp", "Algebra abstrakcyjna: Grupy", "Analiza - ciągi liczbowe", "Granica ciągu", "Twierdzenie o trzech ciągach", "Szeregi liczbowe", "Kryteria zbieżności szeregów",
    "Szeregi potęgowe i promień zbieżności", "Granica funkcji w punkcie", "Asymptoty funkcji", "Ciągłość funkcji", "Pochodna funkcji - definicja", "Wzory na pochodne funkcji elementarnych", "Reguły różniczkowania (Łańcuchowa, Ilorazu)", "Twierdzenie de L'Hospitala", "Ekstrema lokalne", "Punkt przegięcia i wypukłość",
    "Badanie przebiegu zmienności funkcji", "Twierdzenie Lagrange'a (Wartość średnia)", "Wzór Taylora i Maclaurina", "Całka nieoznaczona", "Wzory całkowe", "Całkowanie przez części", "Całkowanie przez podstawienie", "Całkowanie ułamków prostych", "Całka oznaczona Riemanna", "Zasadnicze twierdzenie rachunku całkowego",
    "Obliczanie pola figur płaskich", "Obliczanie długości krzywej", "Pola i objętości brył obrotowych", "Całki niewłaściwe", "Funkcje wielu zmiennych", "Dziedzina i granica funkcji 2D", "Pochodne cząstkowe", "Gradient funkcji", "Pochodna kierunkowa", "Ekstrema lokalne 2D",
    "Metoda mnożników Lagrange'a", "Całka podwójna", "Współrzędne biegunowe", "Całka potrójna", "Współrzędne walcowe i sferyczne", "Całki krzywoliniowe", "Twierdzenie Greena", "Całki powierzchniowe", "Twierdzenie Gaussa-Ostrogradskiego", "Twierdzenie Stokesa",
    "RRZ - o zmiennych rozdzielonych", "RRZ liniowe rzędu pierwszego", "RRZ rzędu drugiego", "Metoda przewidywań", "Przekształcenie Laplace'a", "Równania Różniczkowe Cząstkowe (RRC)", "Szeregi Fouriera", "Równania różnicowe (dyskretne)", "Optymalizacja nieliniowa podst", "Przestrzenie Hilberta (Zarys)",
    "Topologia - pojęcia podstawowe", "Kombinatoryka", "Permutacje i Wariacje", "Dwumian Newtona", "Grafy i drzewa", "Algorytmy grafowe (Dijkstra)", "Teoria Liczb", "Kongruencje", "Kryptografia RSA (Matematyka)", "Teoria Gier (Równowaga Nasha)"
  ],
  "Matematyka (Statystyka i Prawdopodobieństwo)": [
    "Przestrzeń zdarzeń elementarnych", "Prawdopodobieństwo klasyczne", "Kombinatoryka w prawdopodobieństwie", "Prawdopodobieństwo warunkowe", "Niezależność zdarzeń", "Wzór na prawdopodobieństwo całkowite", "Twierdzenie Bayesa", "Zmienna losowa dyskretna", "Rozkład dwumianowy", "Rozkład Poissona",
    "Rozkład hipergeometryczny", "Zmienna losowa ciągła", "Funkcja gęstości", "Dystrybuanta", "Wartość oczekiwana", "Wariancja i odchylenie standardowe", "Rozkład jednostajny", "Rozkład wykładniczy", "Rozkład normalny (Krzywa Gaussa)", "Standaryzacja rozkładu normalnego",
    "Momenty zmiennej losowej", "Skośność i kurtoza", "Zmienne losowe wielowymiarowe", "Rozkład brzegowy i warunkowy", "Kowariancja", "Współczynnik korelacji Pearsona", "Niezależność zmiennych losowych", "Nierówność Czebyszewa", "Prawa wielkich liczb", "Centralne Twierdzenie Graniczne (CTG)",
    "Łańcuchy Markowa", "Macierz przejścia", "Stany absorbujące", "Procesy stochastyczne wstęp", "Błądzenie losowe", "Proces Poissona", "Wstęp do statystyki opisowej", "Szeregi rozdzielcze", "Miary położenia (Średnia, Mediana, Dominanta)", "Miary rozproszenia (Wariancja, Rozstęp)",
    "Kwantyle i percentyle", "Wykresy pudełkowe (Boxplot)", "Wstęp do statystyki matematycznej", "Estymacja punktowa", "Metoda największej wiarogodności (MLE)", "Metoda momentów", "Własności estymatorów (Zgodność, Nieobciążoność)", "Estymacja przedziałowa", "Przedziały ufności dla średniej", "Przedziały ufności dla wariancji",
    "Przedziały ufności dla wskaźnika struktury", "Wstęp do testowania hipotez", "Hipoteza zerowa i alternatywna", "Błędy pierwszego i drugiego rodzaju", "Poziom istotności i p-value", "Moc testu", "Testy parametryczne", "Test t-Studenta dla jednej średniej", "Test t-Studenta dla dwóch średnich", "Testy dla wariancji (Test F)",
    "Testy nieparametryczne wstęp", "Test niezależności chi-kwadrat", "Test zgodności chi-kwadrat", "Test Kołmogorowa-Smirnowa", "Test Shapiro-Wilka (normalność)", "Test U Manna-Whitneya", "Test Wilcoxona", "Test Kruskala-Wallisa", "Analiza wariancji (ANOVA) jednoczynnikowa", "ANOVA dwuczynnikowa",
    "Wstęp do analizy regresji", "Prosta regresja liniowa", "Metoda Najmniejszych Kwadratów (OLS)", "Ocena dopasowania (R-kwadrat)", "Testowanie istotności współczynników regresji", "Regresja wieloraka", "Współliniowość zmiennych objaśniających", "Regresja logistyczna wstęp", "Analiza Szeregów Czasowych wstęp", "Dekompozycja szeregu czasowego",
    "Wygładzanie wykładnicze", "Model autoregresji (AR)", "Model średniej ruchomej (MA)", "Modele ARMA i ARIMA", "Autokorelacja", "Statystyka bayesowska wstęp", "Rozkłady a priori i a posteriori", "Wnioskowanie bayesowskie", "Symulacje Monte Carlo", "Generatory liczb pseudolosowych",
    "Metody Resamplingu", "Bootstrap", "Jackknife", "Statystyka przestrzenna", "Design of Experiments (DoE) w statystyce", "Statystyka w badaniach medycznych (Biostatystyka)", "Modele przeżycia (Kaplan-Meier)", "Wizualizacja niepewności", "Błędy interpretacji statystycznej", "Paradoks Simpsona"
  ]
});
window.KnowledgeTree = window.KnowledgeTree || {};
Object.assign(window.KnowledgeTree, {
  "IT: Front-End (Podstawy HTML/CSS/JS)": [
    "Jak działa Internet (HTTP, DNS)", "Przeglądarki i silniki renderujące", "Wprowadzenie do HTML5", "Struktura dokumentu HTML", "Semantyczne tagi HTML5", "Formularze i walidacja", "Atrybuty globalne", "Multimedia w HTML", "SVG i grafika wektorowa", "Wprowadzenie do CSS3",
    "Kaskadowość i specyficzność (Specificity)", "Box Model", "Pozycjonowanie", "Display (block, inline)", "Z-index i konteksty stosu", "Flexbox - kontenery i elementy", "CSS Grid - podstawa siatki", "CSS Grid - pozycjonowanie", "Responsywne projektowanie (RWD)", "Media Queries",
    "Jednostki względne", "Mobile First Design", "Zmienne CSS", "Pseudoklasy", "Pseudoelementy", "CSS Transitions (Przejścia)", "CSS Animations (Keyframes)", "Typografia webowa", "Wprowadzenie do JavaScript (ES6+)", "Zmienne (let, const)",
    "Typy danych w JS", "Operatory i rzutowanie", "Instrukcje warunkowe", "Pętle", "Funkcje deklaratywne", "Arrow functions", "Zasięg zmiennych i Closures", "Hoisting w JS", "Obiekty", "Tablice",
    "Metody tablicowe (map, filter)", "Destrukturyzacja", "Operator Spread i Rest", "Wprowadzenie do DOM", "Pobieranie elementów DOM", "Modyfikacja elementów z JS", "Tworzenie węzłów DOM", "Obsługa zdarzeń (Events)", "Delegacja zdarzeń", "Event Loop (Event Loop)",
    "Callbacks", "Promises", "Async i Await", "Fetch API", "Obsługa błędów (try-catch)", "Format JSON", "Web Storage (Local, Session)", "Ciasteczka (Cookies)", "Moduły ES6 (import/export)", "Wzorce projektowe podst (Moduł)",
    "Debugowanie JS w DevTools", "Konsola i Network tab", "System kontroli wersji (Git)", "Git commit/push/pull", "Platformy (GitHub/Netlify)", "NPM i Yarn podst", "Plik package.json", "Prettier i ESLint", "Preprocesory (SASS/SCSS)", "Zagnieżdżanie w SASS",
    "Architektura CSS (BEM)", "Dostępność (a11y) wstęp", "Atrybuty ARIA", "Czytniki ekranowe", "Wydajność webowa - wstęp", "Lighthouse i Web Vitals", "Optymalizacja obrazów (WebP)", "Lazy Loading zasobów", "Krytyczny CSS", "Minifikacja kodu",
    "Podstawy SEO technicznego", "Zabezpieczenia (XSS podst)", "CORS", "Web Components wstęp", "Shadow DOM", "Custom Elements", "HTML Templates", "Architektura Jamstack podst", "PWA podst", "Manifest JSON PWA",
    "Service Workers podst", "Rozwój kariery Junior Front-End", "Wybór frameworka", "DOM Manipulation advanced", "Prototypy w JS", "Klawiatura i a11y focus", "CSS w JS", "Stylowanie formularzy", "Animacje z JS", "SASS Mixins"
  ],
  "IT: React i Nowoczesny UI": [
    "Wprowadzenie do React i Virtual DOM", "Deklaratywne UI", "Instalacja (Vite vs CRA)", "Składnia JSX", "Wyrażenia w JSX", "Warunkowe renderowanie", "Renderowanie list i klucze", "Komponenty funkcyjne", "Przekazywanie Props", "Props.children i kompozycja",
    "Stan lokalny (useState)", "Asynchroniczność stanu", "Zdarzenia (Events) w React", "Formularze kontrolowane", "Formularze niekontrolowane", "Cykl życia komponentu (podstawy)", "Efekty uboczne (useEffect)", "Dependency array", "Czyszczenie efektów (Cleanup)", "Tworzenie własnych Hooków",
    "Zarządzanie złożonym stanem (useReducer)", "Context API (Kontekst)", "Prop Drilling", "Memoizacja wartości (useMemo)", "Memoizacja funkcji (useCallback)", "Optymalizacja renderowania (React.memo)", "Refy w React (useRef)", "Forwardowanie Refów (forwardRef)", "useImperativeHandle", "useLayoutEffect",
    "Portal (React.createPortal)", "Suspense i lazy loading", "Error Boundaries", "Routing w SPA", "React Router podst", "Route i Link", "Parametry w URL", "Nawigacja programowa", "Zagnieżdżone ścieżki", "Ochrona ścieżek",
    "Stan globalny - kiedy używać?", "Redux - koncepcje", "Redux Toolkit (RTK)", "Tworzenie Slice'ów w RTK", "Asynchroniczne thunki", "Zustand - nowoczesny stan", "Jotai i atomy", "Recoil wstęp", "Komunikacja z API w React", "React Query (TanStack Query)",
    "Pobieranie i cachowanie", "Mutacje w React Query", "SWR", "Stylowanie w React: CSS Modules", "CSS-in-JS: Styled Components", "Tailwind CSS z Reactem", "Biblioteki UI (Material UI)", "Chakra UI", "Framer Motion - animacje", "React Hook Form",
    "Walidacja (Yup, Zod)", "Storybook w React", "Testowanie w React", "React Testing Library", "Testowanie interakcji", "Mockowanie API (MSW)", "Testy snapshotowe", "Architektura React", "Struktura katalogów", "Wzorce (HOC, Render Props)",
    "Separacja logiki od UI", "Zaawansowane Hooki", "React 18: Concurrent Features", "Server Components w React (RSC)", "Frameworki pełnostackowe (Wstęp)", "Next.js - App Router", "Renderowanie po stronie serwera (SSR)", "Generowanie statyczne (SSG)", "Optymalizacja obrazów (Next)", "Next.js API Routes",
    "Gatsby.js", "Remix loader koncepcje", "React Native wstęp", "Architektura React Native", "Mikrofrontendy w React", "Typowanie w React z TypeScript", "Props i State z TypeScript", "Typowanie zdarzeń TS", "Migracja do TS", "PWA z Reactem",
    "Profiling w DevTools", "CI/CD dla React", "React Compiler (wstęp)", "Serwowanie statyczne vs dynamiczne", "Aplikacje izomorficzne", "Pre-rendering", "Optymalizacja Hydracji", "React Developer Tools", "Strict Mode", "Przyszłość ekosystemu React"
  ],
  "IT: Front-End Architektura i Wydajność": [
    "Wzorce architektoniczne UI", "Atomic Design podst", "Atomic Design zaawansowane", "Micro-Frontends koncepcja", "Module Federation (Webpack)", "Iframe vs Web Components", "Niestandardowe elementy", "Shadow DOM i izolacja", "LitHTML", "Zarządzanie stanem globalnym (wzorce)",
    "CQRS na frontendzie", "Event Sourcing w JS", "Architektura Flux", "Redux pod maską", "Middleware w Redux", "Optymalizacja selektorów (Reselect)", "XState i maszyny stanów", "Zarządzanie cachem po stronie klienta", "React Query architektura", "Apollo Client i GraphQL cache",
    "Offline-first architecture", "IndexedDB - operacje", "Service Workers strategie cachowania", "WebSockets skalowanie", "Server-Sent Events (SSE)", "WebRTC i P2P", "Wydajność: Krytyczna ścieżka renderowania", "Wydajność: Paint i Layout", "Web Vitals (LCP, FID, CLS, INP)", "Analiza wąskiego gardła (Lighthouse)",
    "Profilowanie pamięci DevTools", "Wycieki pamięci w JS", "Odśmiecanie pamięci (GC V8)", "Optymalizacja silnika V8", "WebAssembly (Wasm) wprowadzenie", "Integracja Rust z JS", "Wielowątkowość w przeglądarce", "Web Workers", "Shared Workers", "AudioWorklet",
    "WebGL kontekst", "Shadery (GLSL) na frontendzie", "Optymalizacja animacji (rAF)", "CSS GPU Acceleration", "Hardware wideo dekodowanie", "Lazy Loading zaawansowany", "Code Splitting", "Tree Shaking", "Pnpm i Yarn Berry", "Monorepo (Nx, Turborepo)",
    "Vite i esbuild", "SWC kompilator", "Optymalizacja zasobów statycznych", "Formaty obrazów (AVIF, WebP)", "Kompresja Brotli", "CORS i CSP", "Zabezpieczenia XSS", "Zabezpieczenia CSRF", "Clickjacking protection", "Autoryzacja (JWT, OIDC)",
    "Cookies HttpOnly", "Testy E2E z Playwright", "Cypress intercepcje sieciowe", "Testowanie wydajnościowe CI", "Visual Regression Testing", "Testowanie dostępności", "Architektura Jamstack", "Statyczne generowanie stron", "SSR wyzwania", "Incremental Static Regeneration (ISR)",
    "Streaming SSR", "Hydratacja (Hydration)", "Resumability (Qwik) vs Hydration", "Edge Computing", "Edge Rendering", "Dostępność zaawansowana", "Wzorzec ARIA (Dialog, Grid)", "Zarządzanie focusem", "Czytniki ekranowe optymalizacja", "Internacjonalizacja (i18n)",
    "Lokalizacja (l10n)", "Dark Mode CSS", "Projektowanie systemów designu", "Storybook w monorepo", "Design Tokens", "Wersjonowanie komponentów UI", "Feature Flags na frontendzie", "A/B Testing na kliencie", "Sentry (monitorowanie błędów)", "Analiza logów klienckich",
    "Telemetria UX", "CI dla Front-Endu", "Continuous Deployment", "Migracja systemów Legacy", "Automatyzacja refaktoryzacji (jscodeshift)", "Pisanie własnych pluginów ESLint", "Zarządzanie długiem technicznym frontendu", "BFF (Backend for Frontend)", "Wdrażanie CDN", "Przyszłość architektury"
  ],
  "IT: Python (Core i Zaawansowany)": [
    "Historia Pythona i PEP8", "Środowisko wirtualne (venv)", "Struktura kodu i wcięcia", "Zmienne i podstawowe typy", "Operatory", "f-strings i formatowanie", "Listy i operacje tablicowe", "Krotki (Tuples)", "Słowniki (Dictionaries)", "Zbiory (Sets)",
    "Instrukcje warunkowe", "Pętle (for, while)", "Instrukcje break/continue", "Funkcje wbudowane", "Tworzenie własnych funkcji", "Argumenty *args i **kwargs", "Zasięg zmiennych (LEGB)", "Wyrażenia lambda", "Operacje na plikach (odczyt/zapis)", "Kontekst menedżery (with)",
    "Wyjątki i try-except", "Rzucanie wyjątków (raise)", "Własne wyjątki", "List Comprehensions", "Dict i Set Comprehensions", "Importowanie modułów", "Moduły os, sys, math", "Moduły time i datetime", "Wyrażenia regularne (re)", "Programowanie Obiektowe (OOP) wstęp",
    "Klasy i obiekty (__init__)", "Atrybuty klasy vs instancji", "Dziedziczenie i super()", "Hermetyzacja i właściwości (property)", "Polimorfizm", "Metody magiczne (Dunder)", "Klasy abstrakcyjne (abc)", "Wielodziedziczenie i MRO", "Generatory (yield)", "Iteratory (__iter__, __next__)",
    "Dekoratory funkcji", "Dekoratory z argumentami", "Klasy jako dekoratory", "Typowanie statyczne (typing)", "Typy generyczne i Unie", "JSON w Pythonie", "CSV w Pythonie", "Kopiowanie obiektów (moduł copy)", "Sortowanie obiektów (key)", "Wykorzystanie map i filter",
    "Moduł collections", "Moduł itertools", "Zmienne środowiskowe (dotenv)", "Parsowanie argumentów (argparse)", "Debugowanie (pdb)", "Pylint i Flake8", "Formatowanie Black", "Sprawdzanie typów (Mypy)", "Testy jednostkowe (unittest)", "Framework pytest podstawy",
    "Wielowątkowość (Threading)", "Wieloprocesowość (Multiprocessing)", "Asynchroniczność (asyncio) wstęp", "Event Loop", "Tworzenie funkcji async", "Moduł aiohttp", "Walka z GIL", "Zaawansowane metaprogramowanie", "Dynamiczne tworzenie klas", "Deskryptory (__get__, __set__)",
    "Dekoratory klas i wzorce", "Słabe referencje (weakref)", "Fixture w Pytest", "Mockowanie w testach", "Testowanie asynchroniczne", "Profilowanie (cProfile)", "CLI z Click/Typer", "Zarządzanie pakietami Poetry", "C-Extensions wstęp", "Garbage Collection w Python",
    "Funkcje lru_cache i partial", "Moduł pathlib", "Wirtualne środowiska conda", "Kompilacja Cython", "Tworzenie pakietów (setuptools, wheel)", "Publikacja pakietu na PyPI", "Python AST (Abstract Syntax Trees)", "Python 3.11+ i wydajność", "GIL removal (Nogil)", "Kompilatory JIT (PyPy)"
  ],
  "IT: Backend Engineering i API": [
    "Protokół HTTP", "REST API koncepcje", "Kodowania i nagłówki HTTP", "Metody HTTP (GET, POST, PUT, DELETE)", "Flask - routing i widoki", "Flask - szablony Jinja2", "Flask - rozszerzenia i Middleware", "Django - architektura MVT", "Django - Modele i ORM", "Django - zapytania (Q, F)",
    "Django - migracje baz danych", "Django - Formularze", "Django - Autentykacja", "Django REST Framework (DRF)", "DRF - Serializery", "DRF - ViewSets i Routers", "DRF - Token Auth", "FastAPI - asynchroniczność", "FastAPI - walidacja Pydantic", "FastAPI - Dependency Injection",
    "FastAPI - Swagger/OpenAPI", "FastAPI - zadania w tle", "Bazy relacyjne podst", "SQL i operacje", "SQLAlchemy Core", "SQLAlchemy ORM", "Alembic migracje", "NoSQL w Pythonie (Motor dla MongoDB)", "Asynchroniczny PostgreSQL (asyncpg)", "Redis jako Cache",
    "Systemy kolejkowe podst", "Celery i zadania w tle", "Celery Beat (zadania okresowe)", "RabbitMQ jako broker", "Zabezpieczenia API (CORS, CSP)", "WebSockets w Pythonie", "GraphQL z wykorzystaniem Strawberry", "Mikroserwisy (Nameko, gRPC)", "Autoryzacja JWT", "OAuth 2.0 i OIDC",
    "Hashing haseł (bcrypt)", "Testowanie REST API (Httpx)", "Docker w aplikacjach Python", "Tworzenie Dockerfile", "Wieloetapowe budowanie Docker", "Docker Compose", "CI/CD dla backendu (GitHub Actions)", "Wdrażanie na Heroku/Render", "Serwery WSGI (Gunicorn)", "Serwery ASGI (Uvicorn)",
    "Serverless (AWS Lambda, Zappa)", "Architektura Event-Driven", "Logowanie strukturalne (structlog)", "Monitorowanie błędów Sentry", "Prometheus i Grafana dla Pythona", "Problem zapytań N+1", "Bezstanowość (Stateless API)", "Clean Architecture w Pythonie", "CQRS w Pythonie", "Zarządzanie tajemnicami (Vault)",
    "API Rate Limiting", "API Keys management", "Role-Based Access Control (RBAC)", "Circuit Breaker pattern", "Load balancing backendu", "Application Performance Monitoring (APM)", "Rozwiązywanie martwych blokad (Deadlocks)", "Wdrażanie i wersjonowanie API", "HATEOAS koncepcja", "Caching zaawansowany (Varnish)",
    "Przetwarzanie plików w tle (S3)", "Webhooks implementacja", "Testy obciążeniowe (Locust, k6)", "Budowa SDK dla API", "Przetwarzanie płatności (Stripe API)", "Architektura wielodostępna (Multi-tenant)", "Wyszukiwanie pełnotekstowe (Elasticsearch)", "Bezpieczeństwo deserializacji danych", "Refaktoryzacja legacy backendów", "Web scraping zaawansowany z backendu"
  ],
  "IT: Data Science i Analiza Danych": [
    "Wprowadzenie do Data Science", "Cykl analityczny", "Jupyter Notebook i Colab", "Manipulacja danymi NumPy", "Tablice wielowymiarowe", "Pandas Series i DataFrames", "Indeksowanie w Pandas", "Filtrowanie danych", "Grupowanie (groupby)", "Łączenie danych (Merge/Join)",
    "Oczyszczanie danych", "Kodowanie zmiennych", "Time Series w Pandas", "Wizualizacja: Matplotlib", "Wizualizacja: Seaborn", "Plotly i wykresy interaktywne", "Statystyka opisowa w DS", "Rozkłady prawdopodobieństwa", "Testowanie hipotez (p-value)", "Przedziały ufności",
    "Analiza korelacji", "A/B Testing w biznesie", "SQL dla analityków", "SELECT i JOIN", "Funkcje okna w SQL", "Web Scraping (BeautifulSoup)", "Web Scraping (Selenium)", "API do pobierania danych", "Feature Engineering", "Skalowanie danych",
    "Detekcja wartości odstających", "Redukcja wymiarowości (PCA)", "Scikit-Learn architektura", "Zbiór testowy i treningowy", "Regresja liniowa implementacja", "Ocena modeli regresji (RMSE)", "Regresja logistyczna", "Drzewa decyzyjne klasyfikacja", "Lasy losowe (Random Forests)", "Ocena klasyfikacji (F1, Recall)",
    "Krzywa ROC i AUC", "Kroswalidacja", "Tuning hiperparametrów", "Algorytm K-Najbliższych Sąsiadów", "Maszyny Wektorów Nośnych (SVM)", "Klasteryzacja K-Means", "Klasteryzacja hierarchiczna", "DBSCAN", "Gradient Boosting (XGBoost)", "LightGBM w praktyce",
    "Niezbalansowane dane (SMOTE)", "Analiza Szeregów Czasowych", "Model ARIMA/SARIMA", "Model Prophet", "Interpretowalność modeli (SHAP, LIME)", "Rekomendacje Collaborative Filtering", "Rekomendacje Content-Based", "NLP wstęp do tekstu", "Tokenizacja i stemming", "TF-IDF w praktyce",
    "Analiza sentymentu bazowa", "OpenCV analiza obrazu", "Storytelling danych", "Tableau podstawy", "Power BI podstawy", "Tworzenie aplikacji w Streamlit", "Aplikacje analityczne Dash", "Wdrażanie modeli wstęp", "API dla modelu ML (FastAPI)", "Konteneryzacja projektów DS",
    "Zarządzanie środowiskami Conda", "Sklearn Pipelines", "Git w analityce", "Wstęp do Big Data w DS", "Spark i PySpark podst", "DataFrames w Spark", "Etyka w DS i AI bias", "GDPR i prywatność danych", "MLflow cykl życia", "Wersjonowanie DVC",
    "Automated ML (AutoML)", "TPOT i H2O.ai", "Budowanie portfela Data Science", "Data Literacy dla menedżerów", "Wskaźniki biznesowe (KPI) z danych", "Prezentacja wyników dla niefachowców", "Analiza kohortowa", "LTV i Customer Churn", "RFM Analysis", "Zastosowania DS w marketingu"
  ],
  "IT: Data Engineering i Big Data": [
    "Wprowadzenie do Data Engineering", "Architektura Systemów Danych", "ETL vs ELT", "Modelowanie danych (Schematy)", "Hurtownie Danych (Data Warehouse)", "Data Lake", "Data Lakehouse koncepcja", "Formaty: Parquet", "Formaty: Avro i ORC", "Rozproszone systemy plików (HDFS)",
    "Zaawansowany SQL do transformacji", "Optymalizacja zapytań i indeksowanie", "NoSQL: Magazyny klucz-wartość (Redis)", "NoSQL: Bazy dokumentowe", "NoSQL: Rodziny kolumn (Cassandra)", "NoSQL: Bazy grafowe (Neo4j)", "Apache Hadoop ekosystem", "Apache Spark architektura", "Spark SQL", "Optymalizacja w Spark (Partycjonowanie)",
    "Spark Streaming", "Apache Kafka podst", "Kafka Topics i Brokers", "Kafka Connect", "Apache Flink strumienie", "Apache Beam", "Orchestracja: Apache Airflow", "Airflow DAGs i Operatory", "Airflow zaawansowany XCom", "Dagster i Prefect",
    "Hurtownie chmurowe: Snowflake", "Klonowanie danych w Snowflake", "Google BigQuery", "BigQuery ML", "Amazon Redshift", "Zarządzanie tożsamością i dostępem (IAM)", "Infrastruktura jako kod (Terraform w DE)", "Konteneryzacja procesów DE (Docker)", "Kubernetes w systemach danych", "Transformacja za pomocą dbt",
    "Modelowanie z dbt", "CI/CD dla DE", "Zarządzanie jakością danych", "Great Expectations", "Katalogowanie danych (Data Catalog)", "Lineage danych (Apache Atlas)", "Kolejkowanie (RabbitMQ)", "Architektura Lambda", "Architektura Kappa", "Windowing i Watermarks w streamingu",
    "Apache NiFi", "Change Data Capture (CDC)", "Debezium", "Szyfrowanie danych w locie i spoczynku", "Anonimizacja danych na skale", "Optymalizacja kosztów chmury", "Data Mesh koncepcja", "Data Fabric", "Serverless DE (AWS Lambda)", "Lakehouse: Delta Lake",
    "Lakehouse: Apache Iceberg", "Lakehouse: Apache Hudi", "Databricks Jobs i Notebooks", "Rozwiązywanie problemów w rozproszonych klastrach", "Monitorowanie systemów (Prometheus/Grafana)", "ELK Stack w inżynierii danych", "Ekstrakcja danych z ERP", "Bazy Time Series (InfluxDB)", "Grafy w inżynierii danych", "FastAPI dla warstwy serwowania",
    "Dashboardy Real-time", "Generowanie danych syntetycznych", "Migracja On-Premise do Cloud", "Integracja BI (Tableau/Looker)", "Kultura DataOps", "Query Cost Analysis", "Oddzielenie storage od compute", "Rust i Go w DE", "Wektorowe bazy danych podst", "Wdrażanie ML na produkcję",
    "Feature Store w ML", "Apache Pinot (OLAP)", "Apache Druid", "ClickHouse", "Zarządzanie metastore (Hive Metastore)", "Data Contracts", "FinOps dla inżynierii danych", "Automatyzacja monitorowania SLA", "Rozproszone uczenie na Sparku", "Przyszłość Data Engineeringu"
  ]
});
window.KnowledgeTree = window.KnowledgeTree || {};
Object.assign(window.KnowledgeTree, {
  "IT: AI - Machine Learning (Klasyczne)": [
    "Historia Uczenia Maszynowego", "Algebra liniowa dla ML", "Probabilistyka dla ML", "Przygotowanie danych w ML", "Wybrakowane dane i imputacja", "Normalizacja vs Standaryzacja", "Kodowanie kategoryczne (One-Hot)", "Wykrywanie Outlierów", "Podział na zbiór: Train / Test", "Kroswalidacja K-Fold",
    "Problem Bias-Variance Tradeoff", "Zapobieganie Przeuczeniu (Overfitting)", "Niedouczenie (Underfitting)", "Regularyzacja L1 (Lasso)", "Regularyzacja L2 (Ridge)", "Elastic Net", "Zaawansowana Regresja Liniowa", "Regresja Wielomianowa", "Regresja Logistyczna", "Funkcja Sigmoid",
    "Funkcja straty Cross-Entropy", "Spadek Gradientowy (Gradient Descent)", "Stochastyczny spadek gradientu (SGD)", "Algorytmy optymalizacji (Adam podst)", "Drzewa Decyzyjne", "Entropia i Indeks Gini", "Przycinanie Drzew (Pruning)", "Lasy Losowe (Random Forest)", "Bagging i OOB Error", "Gradient Boosting Machines (GBM)",
    "XGBoost - matematyka i optymalizacja", "LightGBM", "CatBoost dla danych kategorycznych", "K-Najbliższych Sąsiadów (KNN)", "Maszyny Wektorów Nośnych (SVM)", "Kernel Trick w SVM", "Uczenie Nienadzorowane - algorytmy", "Algorytm K-Means", "Dobór K (Elbow Method)", "K-Means++",
    "Hierarchiczna klasteryzacja", "DBSCAN", "HDBSCAN", "Gaussian Mixture Models (GMM)", "Algorytm Expectation-Maximization (EM)", "Redukcja Wymiarowości - teoria", "PCA w detalach liniowych", "SVD w uczeniu maszynowym", "Redukcja Nieliniowa (t-SNE)", "UMAP",
    "Metody Selekcji Cech (Filter / Wrapper)", "Association Rules (Apriori)", "Systemy Rekomendacyjne wstęp", "Filtrowanie Kolaboratywne", "Matrix Factorization", "Filtrowanie oparte na treści (Content-Based)", "Metryki Klasyfikacyjne: Precision / Recall", "F1-Score (Micro, Macro)", "Krzywa ROC", "Obszar AUC",
    "Metryki klasyfikacji wieloklasowej", "Metryki Regresyjne: R2", "Metryki Regresyjne: MAPE, MAE", "Optymalizacja hiperparametrów Grid Search", "Random Search", "Optymalizacja Bayesowska (Optuna)", "Budowanie Pipeline'ów w Scikit-Learn", "Niestandardowe Transformatory", "Metody Ensemble: Stacking", "Metody Ensemble: Blending",
    "Uczenie Pół-nadzorowane", "Active Learning", "Uczenie przez wzmacnianie (RL) - Wstęp", "Proces Decyzyjny Markowa (MDP)", "Równanie Bellmana", "Q-Learning", "Modele klasyfikacji nierównych klas", "Biblioteka Imbalanced-Learn", "Interpretowalność modeli (Black-Box)", "Wyjaśnianie lokalne (LIME)",
    "Wartości SHAP", "PDP i ICE (Zależności cząstkowe)", "Wdrażanie Modeli ML podst", "Konteneryzacja modeli", "MLflow podstawy", "Monitorowanie driftu danych", "Inferencja offline vs online", "Modele krawędziowe (TinyML)", "Federated Learning", "Bezpieczeństwo ML (Adversarial Attacks)",
    "Prywatność Różnicowa (Differential Privacy)", "AutoML: PyCaret", "TPOT", "Ocenianie ryzyka modelu biznesowego", "Ekonomia projektów ML", "Różnice Klasyczny ML vs Deep Learning", "Przygotowanie do wywiadu DS/ML", "Portfel projektów z Klasycznego ML", "Feature Engineering w Sklearn", "Sklearn API dla estymatorów"
  ],
  "IT: AI - Deep Learning i NLP": [
    "Sieci Neuronowe - Perceptron", "Funkcje Aktywacji (ReLU, Sigmoid, Tanh)", "Multi-Layer Perceptron (MLP)", "Algorytm Backpropagation", "Autograd w PyTorch", "Instalacja i środowisko PyTorch", "Tensory i Operacje", "Wdrażanie MLP w PyTorch", "Inicjalizacja wag (Xavier, He)", "Optymalizatory w DL (Adam, AdamW)",
    "Learning Rate Scheduling", "Regularyzacja: Dropout", "Batch Normalization", "Convolutional Neural Networks (CNN)", "Konwolucje (Filtry, Stride, Padding)", "Pooling (Max, Average)", "Architektury CNN: ResNet", "Architektury CNN: EfficientNet", "Transfer Learning w Wizji", "Detekcja obiektów (YOLO)",
    "Segmentacja (U-Net, Mask R-CNN)", "Generative Adversarial Networks (GAN)", "Warianty GAN (StyleGAN)", "Autoenkodery (AE)", "Variational Autoencoders (VAE)", "Wprowadzenie do Przetwarzania Języka (NLP)", "Tokenizacja", "Byte-Pair Encoding (BPE)", "Word Embeddings: Word2Vec", "Embeddings: GloVe i ELMo",
    "Rekurencyjne Sieci Neuronowe (RNN)", "Vanishing Gradient w RNN", "Architektura LSTM", "Architektura GRU", "Modele Sequence-to-Sequence (Seq2Seq)", "Mechanizm Atencji (Attention)", "Architektura Transformer - teoria", "Self-Attention i Multi-Head Attention", "Positional Encoding", "Vision Transformers (ViT)",
    "Modele Enkoderowe (BERT)", "Fine-tuning BERTa", "Named Entity Recognition (NER)", "Modele Dekoderowe (Rodzina GPT)", "Modele Encoder-Decoder (T5)", "Hugging Face Transformers", "Hugging Face Datasets", "Large Language Models (LLMs)", "Prompt Engineering", "Few-shot i Zero-shot learning",
    "Instruction Fine-Tuning", "RLHF (Reinforcement Learning from Human Feedback)", "DPO (Direct Preference Optimization)", "Quantyzacja modeli (INT8, AWQ)", "Parameter-Efficient Fine-Tuning (PEFT)", "LoRA i QLoRA", "Otwarte LLM (Llama, Mistral)", "Retrieval-Augmented Generation (RAG)", "Bazy wektorowe (Chroma, Qdrant)", "Wyszukiwanie hybrydowe (BM25+Wektory)",
    "LangChain", "LlamaIndex", "Agenty AI (ReAct)", "Tool Calling w LLM", "Modele multimodalne", "Dyfuzyjne modele obrazu (Stable Diffusion)", "Architektura DDPM", "ControlNet", "Generacja dźwięku (Suno, AudioCraft)", "Rozpoznawanie mowy (Whisper)",
    "Synteza mowy (ElevenLabs)", "Tłumaczenie maszynowe (NMT)", "Model Serving (TorchServe, vLLM)", "Infrastruktura chmurowa dla AI (GPU)", "Ograniczenia VRAM", "Kompilatory DL (ONNX, TensorRT)", "LLM Jailbreaking i bezpieczeństwo", "Detekcja treści AI", "Bias i etyka AI", "Regulacje prawne (AI Act)",
    "Przyszłość i rozwój AGI", "Kompilatory grafowe (TorchScript)", "Optymalizacja pamięci KVCache", "MoE (Mixture of Experts) podst", "Techniki dekodowania (Beam Search)", "Metryki NLP (BLEU, ROUGE)", "Cross-lingual LLMs", "LLM dla generacji kodu (Codex)", "Autonomiczne Agenty (AutoGPT)", "Przetwarzanie dokumentów i OCR z AI"
  ],
  "Inżynieria Oprogramowania (Wzorce i Zasady)": [
    "Wprowadzenie do inżynierii oprogramowania", "Cykle życia tworzenia oprogramowania (SDLC)", "Paradygmaty programowania (Obiektowe, Funkcyjne)", "Solid Principles - SRP", "Solid Principles - OCP", "Solid Principles - LSP", "Solid Principles - ISP", "Solid Principles - DIP", "Zasada DRY (Don't Repeat Yourself)", "Zasada KISS i YAGNI",
    "Prawa Murphy'ego i niezawodność", "Wzorce kreacyjne (Singleton)", "Wzorce kreacyjne (Factory Method)", "Wzorce kreacyjne (Abstract Factory)", "Wzorce kreacyjne (Builder)", "Wzorce kreacyjne (Prototype)", "Wzorce strukturalne (Adapter)", "Wzorce strukturalne (Bridge)", "Wzorce strukturalne (Composite)", "Wzorce strukturalne (Decorator)",
    "Wzorce strukturalne (Facade)", "Wzorce strukturalne (Proxy)", "Wzorce behawioralne (Observer)", "Wzorce behawioralne (Strategy)", "Wzorce behawioralne (Command)", "Wzorce behawioralne (State)", "Wzorce behawioralne (Template Method)", "Wzorce behawioralne (Mediator, Memento)", "Wzorce architektoniczne wstęp", "MVC (Model-View-Controller)",
    "MVP i MVVM w aplikacjach UI", "Czysta Architektura (Clean Architecture)", "Architektura Hexagonalna", "Architektura Cebulowa (Onion)", "DDD - Ubiquitous Language", "DDD - Bounded Contexts", "DDD - Entities i Value Objects", "DDD - Aggregates i Repositories", "Architektura Event-Driven", "CQRS (Command Query Responsibility)",
    "Event Sourcing", "Architektura Mikroserwisów", "Monolit vs Mikroserwisy", "SOA (Service Oriented Architecture)", "API Gateway Pattern", "Circuit Breaker Pattern", "Bulkhead Pattern", "Strangler Fig Pattern", "Wzorce bezpieczeństwa aplikacji", "Wzorce współbieżności (Actor Model)",
    "Inwersja Kontroli (IoC)", "Dependency Injection (DI) kontenery", "TDD (Test-Driven Development) zasady", "BDD (Behavior-Driven Development) zasady", "Domain-Specific Languages (DSL)", "Refaktoryzacja kodu (Książka Fowlera)", "Zapachy kodu (Code Smells)", "Dług techniczny i jego zarządzanie", "Code Review - najlepsze praktyki", "Pair i Mob Programming",
    "Narzędzia analizy statycznej kodu", "Continuous Integration a jakość", "Dokumentowanie kodu i API", "Architektura oprogramowania (C4 Model)", "Wzorce projektowe w językach funkcyjnych", "Koncepcja Monad w architekturze", "Niemutowalność danych i zalety", "Zwinne modelowanie (Agile Modeling)", "Rozproszone zarządzanie transakcjami (Saga)", "Two-Phase Commit (2PC)",
    "Eventual Consistency (Spójność ostateczna)", "Twierdzenie CAP", "Twierdzenie PACELC", "Wzorce bazodanowe (Sharding)", "Wzorce buforowania (Cache Aside)", "Rate Limiting i Throttling", "Idempotentność API", "HATEOAS", "Dobre praktyki logowania", "Tracing rozproszony (OpenTelemetry)",
    "Health Checks i metryki aplikacji", "Zarządzanie konfiguracją (12-Factor App)", "Przenośność aplikacji", "Optymalizacja algorytmiczna (Złożoność O)", "Analiza wycieków pamięci", "Koncepcja Zero Trust Architecture", "Testowanie mutacyjne architektoniczne", "Analiza zależności i moduły", "Automatyzacja standardów kodu", "Zarządzanie cyklem wydawniczym",
    "Feature Toggles (Flagi funkcji)", "A/B Testing od strony kodu", "AI w kodowaniu i inżynierii", "Prawo Conwaya", "Anti-corruption Layer", "Bounded context mapping", "Systemy rozproszone - czas logiczny", "Gossip Protocols", "Consensus Algorithms (Raft/Paxos)", "Ewolucyjna Architektura (Evolutionary Architecture)"
  ],
  "Inżynieria Wymagań i Testowanie": [
    "Wstęp do Inżynierii Wymagań", "Rola Analityka Biznesowego (BA)", "Cykl życia wymagania", "Identyfikacja interesariuszy", "Elicytacja wymagań (Wywiady)", "Elicytacja wymagań (Warsztaty i ankiety)", "Obserwacja i analiza dokumentacji", "Wymagania biznesowe vs systemowe", "Wymagania funkcjonalne", "Wymagania niefunkcjonalne (Wydajność)",
    "Specyfikacja wymagań (SRS)", "User Stories i Kryteria Akceptacji", "Use Cases (Przypadki Użycia)", "UML w modelowaniu wymagań", "Modelowanie procesów (BPMN)", "Walidacja i Weryfikacja wymagań", "Macierz Śledzenia Wymagań (Traceability Matrix)", "Zarządzanie zmianą w wymaganiach", "Narzędzia do wymagań (Jira, Confluence)", "Wymagania w metodykach zwinnych vs Waterfall",
    "Prototypowanie i makiety", "BDD (Gherkin syntax)", "Wprowadzenie do Testowania Oprogramowania", "Piramida Testów (Teoria)", "Zasady testowania oprogramowania", "Testy jednostkowe (Unit Tests)", "Testy integracyjne", "Testy systemowe", "Testy akceptacyjne (UAT)", "Testowanie czarnoskrzynkowe (Black-box)",
    "Testowanie białoskrzynkowe (White-box)", "Testowanie szarnoskrzynkowe (Grey-box)", "Techniki testów (Wartości brzegowe)", "Podział na klasy równoważności", "Testowanie oparte na decyzjach", "Testowanie przejść między stanami", "Pokrycie kodu (Code Coverage)", "Testowanie regresyjne", "Testowanie eksploracyjne", "Testowanie dymne i sanity (Smoke & Sanity)",
    "Testowanie bezpieczeństwa", "Testowanie wydajnościowe (Performance)", "Testy obciążeniowe (Load)", "Testy przeciążeniowe (Stress)", "Testowanie dostępności (Accessibility)", "Testowanie użyteczności (Usability)", "Testowanie A/B w QA", "Automatyzacja testów - wprowadzenie", "Narzędzia (Selenium)", "Narzędzia (Playwright, Cypress)",
    "Testowanie API (Postman, REST Assured)", "Mockowanie i Stubowanie", "Środowiska testowe", "Zarządzanie danymi testowymi (TDM)", "Bug Tracking (Zgłaszanie błędów)", "Cykl życia defektu", "Miary jakości w testowaniu", "Testowanie ciągłe w CI/CD", "Shift-Left Testing", "Testowanie na produkcji (Chaos Engineering)",
    "Certyfikacja ISTQB", "Rola QA w zespołach Agile", "Trzy Amigo w Agile", "TDD w praktyce inżynierskiej", "BDD z narzędziami (Cucumber)", "Modelowanie zagrożeń z analizą wymagań", "Ocena ryzyka w QA", "Testy mutacyjne kodu", "Testy end-to-end w mikrousługach", "Kontraktowe testowanie API (Pact)",
    "Zwinne zamykanie zadań a testowanie", "Utrzymanie skryptów automatycznych", "Wzorce projektowe (Page Object Model)", "Data-Driven Testing", "Keyword-Driven Testing", "Przeglądy kodu jako testy statyczne", "Audyty bezpieczeństwa w inżynierii", "Prawo RODO a wymagania analityczne", "Dostępność WCAG 2.1 w testach", "Zarządzanie testami wieloplatformowymi",
    "AI w generowaniu przypadków testowych", "AI w automatycznym testowaniu (Auto-healing)", "Organizacja zespołu QA", "Defect Triage", "Techniki mapowania procesów", "Business Rules Engine z wymaganiami", "User Experience (UX) w analityce", "Szkice i wireframe'y (Figma)", "Testowanie gier i 3D wstęp", "Testowanie mobilne (Appium)"
  ],
  "Inżynieria DevOps i Cloud": [
    "Kultura DevOps (CAMS)", "Historia DevOps a Agile", "Rola Inżyniera DevOps", "Wprowadzenie do kontroli wersji (Git zaawansowany)", "Strategie branchowania (GitFlow, Trunk-Based)", "Ciągła Integracja (CI)", "Ciągłe Dostarczanie (CD)", "Ciągłe Wdrażanie (Continuous Deployment)", "Narzędzia CI/CD (Jenkins)", "Narzędzia CI/CD (GitLab, GitHub Actions)",
    "Infrastruktura jako Kod (IaC)", "Wprowadzenie do Terraform", "Moduły i State w Terraform", "Ansible dla konfiguracji", "Chef i Puppet", "Konteneryzacja (Docker)", "Dockerfile optymalizacja (Multi-stage)", "Rejestry kontenerów (Docker Hub, ECR)", "Wprowadzenie do Orkiestracji (Kubernetes)", "K8s: Pody, Deploymenty, Serwisy",
    "K8s: Ingress i zarządzanie ruchem", "K8s: ConfigMaps i Secrets", "K8s: Helm (Menedżer pakietów)", "K8s: Skalowanie aplikacji (HPA)", "K8s: Zarządzanie stanem (StatefulSets)", "K8s: Architektura klastra", "Wprowadzenie do Cloud Computing", "IaaS, PaaS, SaaS", "AWS - Podstawy (EC2, S3, VPC)", "AWS - IAM i bezpieczeństwo",
    "AWS - RDS i bazy w chmurze", "AWS - Lambda i Serverless", "Azure - Podstawy", "GCP - Podstawy", "Cloud Native Architecture", "Sieci w chmurze (VPC, Podsieci)", "Load Balancers (ALB, NLB)", "DNS Zarządzanie (Route 53)", "CDN i dystrybucja treści", "Monitorowanie systemów (Prometheus)",
    "Wizualizacja logów (Grafana)", "Zarządzanie logami (ELK Stack)", "Logowanie w chmurze (CloudWatch, Datadog)", "Tracing (Jaeger, Zipkin)", "Inżynieria Niezawodności (SRE)", "Wskaźniki SLI, SLO i SLA", "Error Budgets w SRE", "Zwinne reagowanie na incydenty", "On-call i PagerDuty", "Chaos Engineering",
    "Zabezpieczanie infrastruktury (DevSecOps)", "Skanowanie kontenerów i kodu (Trivy)", "Wdrażanie (Blue-Green Deployment)", "Canary Releases", "A/B Deployments", "Feature Toggles w CD", "Optymalizacja kosztów chmurowych (FinOps)", "Automatyzacja zarządzania certyfikatami", "GitOps (ArgoCD, Flux)", "Service Mesh (Istio, Linkerd)",
    "Bezpieczeństwo K8s (RBAC)", "Serverless Containers (Fargate)", "Chmury hybrydowe i Multi-Cloud", "Zarządzanie tajemnicami (HashiCorp Vault)", "IaC z Pulumi", "Obliczenia brzegowe (Edge Computing)", "Wdrażanie baz danych bez przestojów", "Immutable Infrastructure", "Architektura zorientowana na zdarzenia w DevOps", "Integracja ML w DevOps",
    "Automatyzacja zadań powtarzalnych (Bash, Python)", "Narzędzia testowania infrastruktury (Terratest)", "Kultura post-mortem (Blameless)", "Budowanie zespołu SRE", "Zarządzanie cyklem życia klastra K8s", "Pulum / CDK vs Terraform", "Architektura sieci Zero Trust", "Kontrola kosztów klastrów (Kubecost)", "Podstawy bezpieczeństwa sieci (Firewalls)", "Automatyzacja polityk dostępu (OPA)"
  ],
  "Inżynieria Systemów i Architektura": [
    "Wprowadzenie do architektury systemów", "Rola Architekta Systemowego", "Cechy dobrej architektury (Skalowalność, Niezawodność)", "Architektura Monolityczna", "Rozproszona architektura", "Mikroserwisy (Wzorce i anty-wzorce)", "Serverless Architecture", "Architektura sterowana zdarzeniami (Event-Driven)", "SOA (Service-Oriented Architecture)", "P2P (Peer-to-Peer)",
    "Model C4 do wizualizacji architektury", "Viewpoints w architekturze (4+1 View Model)", "Projektowanie API (RESTful vs GraphQL vs gRPC)", "Zarządzanie stanem (Bezstanowość API)", "Twierdzenie CAP i jego implikacje", "Twierdzenie PACELC", "Wzorce spójności (Strong vs Eventual)", "Dwie fazy commitu (2PC)", "Wzorzec Saga dla transakcji", "CQRS",
    "Event Sourcing", "Skalowalność pionowa (Scale-Up)", "Skalowalność pozioma (Scale-Out)", "Wzorce Load Balancingu", "Odciążanie SSL (SSL Offloading)", "CDN z perspektywy architektonicznej", "Architektura baz relacyjnych vs NoSQL", "Sharding baz danych", "Partycjonowanie danych", "Replikacja (Master-Slave, Multi-Master)",
    "Strategie Cache'owania (Write-Through, Cache-Aside)", "Wzorce komunikacji (Synchroniczna vs Asynchroniczna)", "Systemy kolejkowe (Kafka, RabbitMQ)", "API Gateway Pattern", "Service Mesh koncepcja", "Circuit Breaker Pattern", "Retry and Timeout Patterns", "Bulkhead Pattern", "Bezpieczeństwo architektoniczne (Zero Trust)", "Identity and Access Management (IAM)",
    "SSO, OAuth2 i OIDC", "Architektura IAM (Identity Provider)", "Modelowanie zagrożeń w systemach rozproszonych", "Architektura odporna na awarie (Fault Tolerance)", "Disaster Recovery i High Availability (HA)", "RTO i RPO", "Geo-Redundancy", "Wdrażanie systemów ciągłego monitorowania", "Logowanie scentralizowane i Tracing", "Optymalizacja i profiling systemowy",
    "Projektowanie infrastruktury chmurowej", "Domain-Driven Design (Architektura biznesowa)", "Identyfikacja Bounded Contexts", "Integracja systemów Legacy", "Wzorzec Strangler Fig", "Enterprise Service Bus (ESB)", "Zarządzanie cyklem życia architektury (ADR)", "Governance i standardy korporacyjne", "Architektura multi-tenant (SaaS)", "Izolacja danych w SaaS",
    "Rate Limiting w rozproszonych systemach", "Architektura hybrydowa", "Zarządzanie danymi podstawowymi (Master Data)", "Architektura Lakehouse dla architekta", "Wpływ DevOps na architekturę", "CI/CD z perspektywy zmian architektonicznych", "Infrastruktura jako kod w designie", "Edge Computing dla niskich opóźnień", "Wirtualizacja i kontenery - wpływ na design", "Zrównoważony rozwój i Green IT",
    "AI wspierające architekturę systemów", "Ewolucyjna Architektura", "Architektura zwinna (Agile Architecture)", "Wybór technologii (Technology Radar)", "Rozwiązywanie problemu Vendor Lock-in", "Skalowalność ludzka (Prawo Conwaya)", "Platform Engineering a architektura", "Wpływ Web3 na architekturę systemów", "Integracje B2B i protokoły wymiany", "Architektury bezpieczne z natury (Secure by design)"
  ],
  "Inżynieria Danych i MLOps": [
    "Cykl życia modelu ML", "Różnice między MLOps a tradycyjnym DevOps", "Rola Inżyniera MLOps", "Architektura potoków ML", "Wersjonowanie danych (DVC)", "Rejestr modeli (Model Registry - MLflow)", "Śledzenie eksperymentów ML", "Git dla Data Science", "Konteneryzacja modeli z użyciem Docker", "Izolacja środowisk ML",
    "Architektury treningowe w chmurze (SageMaker)", "Zarządzanie hiperparametrami w skali", "Reprodukowalność badań ML", "Wdrażanie modeli ML (Model Serving)", "Modele w postaci REST API (FastAPI)", "Modele w postaci serwisu gRPC", "Inferencja w czasie rzeczywistym vs Batch", "Serwery inferencyjne (NVIDIA Triton)", "Skalowanie serwerów ML z Kubernetes", "ML w Edge Computing",
    "Monitorowanie działania modeli na produkcji", "Dryft danych (Data Drift) detekcja", "Dryft koncepcji (Concept Drift)", "Metryki produkcyjne modeli ML", "Continuous Training (Ciągłe Uczenie)", "Pipeline'y Kubeflow", "Apache Airflow w potokach ML", "Orchestracja modeli za pomocą Dagster", "Zarządzanie funkcjami modeli (Feature Store)", "Feast i Hopsworks dla Feature Store",
    "Jakość danych dla AI (Data Quality w ML)", "CI/CD dla modeli ML (GitHub Actions)", "Automatyzacja wdrażania (Shadow, Canary)", "Testowanie modeli ML (Testy behawioralne)", "Ocena wydajności API ML", "Optymalizacja kosztów chmury (GPU i TPU)", "FinOps w AI", "Przetwarzanie danych na skale (Delta Lake)", "Lakehouse architecture w AI", "Automatyzacja A/B Testing dla modeli",
    "LLMOps (Duże Modele Językowe)", "Finetuning LLM w potokach CI/CD", "Optymalizacja sprzętowa modeli (TensorRT, ONNX)", "Kompresja modeli", "Kwantyzacja (INT8, FP16 w produkcji)", "Distillation (Destylacja) modeli na produkcję", "Caching odpowiedzi dla LLM", "Zarządzanie zapytaniami z Rate Limiting", "LangSmith do monitorowania RAG", "Wektoryzacja bazy danych produkcyjnych",
    "Pinecone/Milvus w środowisku produkcyjnym", "Hybrydowe systemy analityczne i operacyjne", "Zapewnienie bezpieczeństwa w potokach ML", "Zabezpieczenia przeciw Adversarial Attacks", "Ochrona danych treningowych", "Audytowanie modeli i Governance", "Explainability (XAI) w produkcji", "Równość i unikanie uprzedzeń", "Architektury Serverless ML", "Analiza powtarzalności potoków",
    "Budowanie zespołu MLOps", "Data Contracts w praktyce", "Metadata Management dla modeli ML", "Zarządzanie środowiskami w AI", "Kultura DataOps a MLOps", "Pętle sprzężenia zwrotnego (Human-in-the-loop)", "Aktywne uczenie w przepływach produkcyjnych", "Ewolucja stosu technologicznego MLOps", "Przyszłość zautomatyzowanego AI na produkcji", "Zarządzanie prawami autorskimi w danych AI",
    "Kompilatory AI i akceleratory AI", "Wykorzystanie inferencji lokalnej (WebAssembly ML)", "Rozproszony trening modeli (Horovod)", "Optymalizacja kosztów inferencji LLM", "Monitorowanie modeli RAG i spójności", "Architektura dla modeli agentowych AI", "Certyfikacja i testy bezpieczeństwa LLM", "Utrzymanie stabilności modeli nieliniowych", "Analiza odchyleń w danych testowych MLOps", "Zarządzanie cyklem starzenia się modelu"
  ]
});
